package com.sown.outerrim.dimension.scarif;

import net.minecraft.init.Blocks;
import net.minecraft.world.World;

import java.util.Random;

import com.sown.outerrim.dimension.endor.WorldGenEndorTreeBase;

public class WorldGenPalmTree5 extends WorldGenEndorTreeBase {

    @Override
    protected void buildTree(World world, Random rand, int x, int y, int z) {
    	        place(world, x + 0, y + 13, z + 8, Blocks.leaves, 15);
    	        place(world, x + 1, y + 14, z + 7, Blocks.leaves, 15);
    	        place(world, x + 1, y + 14, z + 8, Blocks.leaves, 15);
    	        place(world, x + 1, y + 15, z + 7, Blocks.leaves, 15);
    	        place(world, x + 1, y + 17, z + 1, Blocks.leaves, 15);
    	        place(world, x + 2, y + 11, z + 7, Blocks.leaves, 15);
    	        place(world, x + 2, y + 12, z + 6, Blocks.leaves, 15);
    	        place(world, x + 2, y + 15, z + 6, Blocks.leaves, 15);
    	        place(world, x + 2, y + 15, z + 7, Blocks.leaves, 15);
    	        place(world, x + 2, y + 17, z + 9, Blocks.leaves, 15);
    	        place(world, x + 2, y + 18, z + 2, Blocks.leaves, 15);
    	        place(world, x + 2, y + 18, z + 8, Blocks.leaves, 15);
    	        place(world, x + 3, y + 10, z + 2, Blocks.leaves, 15);
    	        place(world, x + 3, y + 11, z + 2, Blocks.leaves, 7);
    	        place(world, x + 3, y + 12, z + 6, Blocks.leaves, 15);
    	        place(world, x + 3, y + 15, z + 6, Blocks.leaves, 15);
    	        place(world, x + 3, y + 17, z + 2, Blocks.leaves, 15);
    	        place(world, x + 3, y + 18, z + 2, Blocks.leaves, 15);
    	        place(world, x + 3, y + 18, z + 7, Blocks.leaves, 15);
    	        place(world, x + 4, y + 11, z + 3, Blocks.leaves, 15);
    	        place(world, x + 4, y + 12, z + 3, Blocks.leaves, 15);
    	        place(world, x + 4, y + 12, z + 5, Blocks.leaves, 15);
    	        place(world, x + 4, y + 12, z + 11, Blocks.leaves, 15);
    	        place(world, x + 4, y + 13, z + 9, Blocks.leaves, 7);
    	        place(world, x + 4, y + 13, z + 10, Blocks.leaves, 15);
    	        place(world, x + 4, y + 14, z + 5, Blocks.leaves, 15);
    	        place(world, x + 4, y + 14, z + 6, Blocks.leaves, 15);
    	        place(world, x + 4, y + 15, z + 6, Blocks.leaves, 15);
    	        place(world, x + 4, y + 16, z + 4, Blocks.leaves, 15);
    	        place(world, x + 4, y + 17, z + 3, Blocks.leaves, 15);
    	        place(world, x + 4, y + 17, z + 7, Blocks.leaves, 15);
    	        place(world, x + 4, y + 18, z + 7, Blocks.leaves, 15);
    	        place(world, x + 5, y + 0, z + 7, Blocks.log, 15);
    	        place(world, x + 5, y + 1, z + 7, Blocks.log, 15);
    	        place(world, x + 5, y + 2, z + 7, Blocks.log, 15);
    	        place(world, x + 5, y + 3, z + 7, Blocks.log, 15);
    	        place(world, x + 5, y + 4, z + 7, Blocks.log, 15);
    	        place(world, x + 5, y + 5, z + 6, Blocks.log, 15);
    	        place(world, x + 5, y + 5, z + 7, Blocks.log, 15);
    	        place(world, x + 5, y + 6, z + 6, Blocks.log, 15);
    	        place(world, x + 5, y + 7, z + 6, Blocks.log, 15);
    	        place(world, x + 5, y + 8, z + 6, Blocks.log, 15);
    	        place(world, x + 5, y + 9, z + 6, Blocks.log, 15);
    	        place(world, x + 5, y + 13, z + 3, Blocks.leaves, 15);
    	        place(world, x + 5, y + 13, z + 5, Blocks.leaves, 15);
    	        place(world, x + 5, y + 13, z + 9, Blocks.leaves, 7);
    	        place(world, x + 5, y + 14, z + 5, Blocks.leaves, 15);
    	        place(world, x + 5, y + 14, z + 6, Blocks.leaves, 15);
    	        place(world, x + 5, y + 14, z + 7, Blocks.leaves, 15);
    	        place(world, x + 5, y + 14, z + 8, Blocks.leaves, 7);
    	        place(world, x + 5, y + 14, z + 9, Blocks.leaves, 7);
    	        place(world, x + 5, y + 15, z + 4, Blocks.leaves, 15);
    	        place(world, x + 5, y + 15, z + 5, Blocks.leaves, 15);
    	        place(world, x + 5, y + 16, z + 4, Blocks.leaves, 15);
    	        place(world, x + 5, y + 16, z + 6, Blocks.leaves, 15);
    	        place(world, x + 5, y + 17, z + 6, Blocks.leaves, 15);
    	        place(world, x + 6, y + 0, z + 7, Blocks.log, 15);
    	        place(world, x + 6, y + 0, z + 8, Blocks.log, 15);
    	        place(world, x + 6, y + 1, z + 8, Blocks.log, 15);
    	        place(world, x + 6, y + 9, z + 5, Blocks.log, 15);
    	        place(world, x + 6, y + 10, z + 5, Blocks.log, 15);
    	        place(world, x + 6, y + 11, z + 5, Blocks.log, 15);
    	        place(world, x + 6, y + 12, z + 5, Blocks.log, 15);
    	        place(world, x + 6, y + 12, z + 6, Blocks.leaves, 15);
    	        place(world, x + 6, y + 13, z + 4, Blocks.leaves, 15);
    	        place(world, x + 6, y + 13, z + 5, Blocks.log, 15);
    	        place(world, x + 6, y + 14, z + 4, Blocks.leaves, 15);
    	        place(world, x + 6, y + 14, z + 5, Blocks.leaves, 15);
    	        place(world, x + 6, y + 14, z + 6, Blocks.leaves, 15);
    	        place(world, x + 6, y + 15, z + 5, Blocks.leaves, 15);
    	        place(world, x + 6, y + 15, z + 6, Blocks.leaves, 15);
    	        place(world, x + 6, y + 16, z + 4, Blocks.leaves, 15);
    	        place(world, x + 6, y + 17, z + 3, Blocks.leaves, 7);
    	        place(world, x + 6, y + 17, z + 4, Blocks.leaves, 7);
    	        place(world, x + 6, y + 18, z + 3, Blocks.leaves, 7);
    	        place(world, x + 7, y + 10, z + 7, Blocks.leaves, 15);
    	        place(world, x + 7, y + 11, z + 6, Blocks.leaves, 15);
    	        place(world, x + 7, y + 11, z + 7, Blocks.leaves, 15);
    	        place(world, x + 7, y + 12, z + 6, Blocks.leaves, 15);
    	        place(world, x + 7, y + 13, z + 3, Blocks.leaves, 15);
    	        place(world, x + 7, y + 13, z + 4, Blocks.leaves, 15);
    	        place(world, x + 7, y + 13, z + 5, Blocks.leaves, 15);
    	        place(world, x + 7, y + 14, z + 4, Blocks.leaves, 15);
    	        place(world, x + 7, y + 14, z + 5, Blocks.leaves, 15);
    	        place(world, x + 7, y + 14, z + 6, Blocks.leaves, 15);
    	        place(world, x + 7, y + 14, z + 7, Blocks.leaves, 15);
    	        place(world, x + 7, y + 15, z + 4, Blocks.leaves, 15);
    	        place(world, x + 7, y + 15, z + 6, Blocks.leaves, 15);
    	        place(world, x + 7, y + 16, z + 6, Blocks.leaves, 15);
    	        place(world, x + 7, y + 16, z + 7, Blocks.leaves, 15);
    	        place(world, x + 7, y + 18, z + 3, Blocks.leaves, 15);
    	        place(world, x + 7, y + 19, z + 2, Blocks.leaves, 15);
    	        place(world, x + 7, y + 19, z + 3, Blocks.leaves, 15);
    	        place(world, x + 8, y + 9, z + 7, Blocks.leaves, 15);
    	        place(world, x + 8, y + 12, z + 0, Blocks.leaves, 15);
    	        place(world, x + 8, y + 12, z + 1, Blocks.leaves, 15);
    	        place(world, x + 8, y + 12, z + 5, Blocks.leaves, 15);
    	        place(world, x + 8, y + 13, z + 1, Blocks.leaves, 7);
    	        place(world, x + 8, y + 13, z + 2, Blocks.leaves, 15);
    	        place(world, x + 8, y + 13, z + 8, Blocks.leaves, 15);
    	        place(world, x + 8, y + 14, z + 5, Blocks.leaves, 15);
    	        place(world, x + 8, y + 14, z + 7, Blocks.leaves, 7);
    	        place(world, x + 8, y + 14, z + 8, Blocks.leaves, 15);
    	        place(world, x + 8, y + 15, z + 3, Blocks.leaves, 15);
    	        place(world, x + 8, y + 16, z + 3, Blocks.leaves, 15);
    	        place(world, x + 8, y + 16, z + 5, Blocks.leaves, 15);
    	        place(world, x + 8, y + 17, z + 5, Blocks.leaves, 15);
    	        place(world, x + 8, y + 17, z + 7, Blocks.leaves, 15);
    	        place(world, x + 8, y + 17, z + 8, Blocks.leaves, 15);
    	        place(world, x + 8, y + 18, z + 1, Blocks.leaves, 15);
    	        place(world, x + 9, y + 11, z + 0, Blocks.leaves, 15);
    	        place(world, x + 9, y + 11, z + 4, Blocks.leaves, 15);
    	        place(world, x + 9, y + 12, z + 4, Blocks.leaves, 7);
    	        place(world, x + 9, y + 13, z + 9, Blocks.leaves, 15);
    	        place(world, x + 9, y + 13, z + 10, Blocks.leaves, 7);
    	        place(world, x + 9, y + 14, z + 5, Blocks.leaves, 15);
    	        place(world, x + 9, y + 14, z + 6, Blocks.leaves, 15);
    	        place(world, x + 9, y + 16, z + 2, Blocks.leaves, 15);
    	        place(world, x + 9, y + 16, z + 9, Blocks.leaves, 15);
    	        place(world, x + 9, y + 17, z + 5, Blocks.leaves, 15);
    	        place(world, x + 9, y + 18, z + 4, Blocks.leaves, 15);
    	        place(world, x + 9, y + 18, z + 5, Blocks.leaves, 15);
    	        place(world, x + 10, y + 11, z + 4, Blocks.leaves, 7);
    	        place(world, x + 10, y + 15, z + 1, Blocks.leaves, 7);
    	        place(world, x + 10, y + 15, z + 6, Blocks.leaves, 15);
    	        place(world, x + 10, y + 15, z + 7, Blocks.leaves, 7);
    	        place(world, x + 10, y + 16, z + 1, Blocks.leaves, 15);
    	        place(world, x + 10, y + 18, z + 4, Blocks.leaves, 15);
    	        place(world, x + 11, y + 15, z + 7, Blocks.leaves, 15);
    	        place(world, x + 11, y + 17, z + 3, Blocks.leaves, 15);
    	        place(world, x + 12, y + 14, z + 7, Blocks.leaves, 15);
    }
}
