package com.sown.outerrim.dimension.endor;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.util.AxisAlignedBB;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class WorldGenEndorBunker extends WorldGenerator {
	private static final List<AxisAlignedBB> ALL_PADS = new ArrayList<>();
	private static final int PAD_WIDTH = 22;
	private static final int PAD_LENGTH = 25;
	private static final int BUFFER = 1;
    /* -------- external-mod block look-ups -------- */
    private static Block getBlockByString(String id){
        return (Block)Block.blockRegistry.getObject(id);
    }

    @Override
    public boolean generate(World world, Random rand, int x, int y, int z) {
		final int minX = x - BUFFER;
		final int minZ = z - BUFFER;
		final int maxX = x + PAD_WIDTH + BUFFER - 1;
		final int maxZ = z + PAD_LENGTH + BUFFER - 1;
        int width = 22, length = 25;
        if (!canPlaceOnSolidGround(world, x, y, z, width, length)) return false;

        Block legends_concrete = getBlockByString("legends:concrete");

        generatePart0(world, x, y, z);
		ALL_PADS.add(AxisAlignedBB.getBoundingBox(minX, 0, minZ, maxX, 255, maxZ));
        return true;
    } // generate

    private void generatePart0(World w, int x, int y, int z){
        Block legends_concrete = getBlockByString("legends:concrete");
        place(w, x+20, y+3, z+0, Blocks.vine, 1);
        place(w, x+20, y+8, z+0, Blocks.vine, 0);
        for(int dx=0; dx<22; dx++) place(w, x+dx, y+9, z+0, legends_concrete, 8);
        for(int dx=0; dx<22; dx++) place(w, x+dx, y+10, z+0, Blocks.stone_slab, 5);
        place(w, x+0, y+0, z+1, Blocks.wool, 8);
        for(int dx=1; dx<5; dx++) place(w, x+dx, y+0, z+1, Blocks.stone, 6);
        place(w, x+5, y+0, z+1, Blocks.wool, 8);
        for(int dx=6; dx<8; dx++) place(w, x+dx, y+0, z+1, Blocks.stonebrick, 1);
        for(int dx=8; dx<10; dx++) place(w, x+dx, y+0, z+1, Blocks.stone, 6);
        place(w, x+10, y+0, z+1, Blocks.wool, 8);
        for(int dx=11; dx<15; dx++) place(w, x+dx, y+0, z+1, Blocks.stone, 0);
        place(w, x+15, y+0, z+1, Blocks.wool, 8);
        for(int dx=16; dx<18; dx++) place(w, x+dx, y+0, z+1, Blocks.stone, 6);
        for(int dx=18; dx<20; dx++) place(w, x+dx, y+0, z+1, Blocks.stonebrick, 1);
        place(w, x+20, y+0, z+1, Blocks.wool, 8);
        place(w, x+21, y+0, z+1, Blocks.vine, 2);
        place(w, x+0, y+1, z+1, Blocks.wool, 8);
        place(w, x+1, y+1, z+1, Blocks.stone, 0);
        place(w, x+2, y+1, z+1, Blocks.stone_brick_stairs, 2);
        place(w, x+3, y+1, z+1, Blocks.stone_stairs, 2);
        place(w, x+4, y+1, z+1, Blocks.stonebrick, 1);
        place(w, x+5, y+1, z+1, Blocks.wool, 8);
        place(w, x+6, y+1, z+1, Blocks.stone, 0);
        for(int dx=7; dx<9; dx++) place(w, x+dx, y+1, z+1, Blocks.stone_brick_stairs, 2);
        place(w, x+9, y+1, z+1, Blocks.stone, 6);
        place(w, x+10, y+1, z+1, Blocks.wool, 8);
        place(w, x+11, y+1, z+1, Blocks.stonebrick, 1);
        place(w, x+12, y+1, z+1, Blocks.stone_stairs, 2);
        place(w, x+13, y+1, z+1, Blocks.stone_brick_stairs, 2);
        place(w, x+14, y+1, z+1, Blocks.stone, 0);
        place(w, x+15, y+1, z+1, Blocks.wool, 8);
        place(w, x+16, y+1, z+1, Blocks.stonebrick, 1);
        place(w, x+17, y+1, z+1, Blocks.stone_stairs, 2);
        place(w, x+18, y+1, z+1, Blocks.stone_brick_stairs, 2);
        place(w, x+19, y+1, z+1, Blocks.stone, 0);
        place(w, x+20, y+1, z+1, Blocks.wool, 8);
        place(w, x+0, y+2, z+1, Blocks.wool, 8);
        place(w, x+1, y+2, z+1, Blocks.stone, 0);
        place(w, x+2, y+2, z+1, Blocks.stone_stairs, 2);
        place(w, x+3, y+2, z+1, Blocks.stone_brick_stairs, 2);
        place(w, x+4, y+2, z+1, Blocks.stonebrick, 1);
        place(w, x+5, y+2, z+1, Blocks.wool, 8);
        place(w, x+6, y+2, z+1, Blocks.stonebrick, 1);
        place(w, x+7, y+2, z+1, Blocks.stone_brick_stairs, 2);
        place(w, x+8, y+2, z+1, Blocks.stone_stairs, 2);
        place(w, x+9, y+2, z+1, Blocks.stone, 6);
        place(w, x+10, y+2, z+1, Blocks.wool, 8);
        place(w, x+11, y+2, z+1, Blocks.stonebrick, 1);
        for(int dx=12; dx<14; dx++) place(w, x+dx, y+2, z+1, Blocks.stone_brick_stairs, 2);
        place(w, x+14, y+2, z+1, Blocks.stone, 0);
        place(w, x+15, y+2, z+1, Blocks.wool, 8);
        place(w, x+16, y+2, z+1, Blocks.stone, 0);
        place(w, x+17, y+2, z+1, Blocks.stone_stairs, 2);
        place(w, x+18, y+2, z+1, Blocks.stone_brick_stairs, 2);
        place(w, x+19, y+2, z+1, Blocks.stone, 0);
        place(w, x+20, y+2, z+1, Blocks.wool, 8);
        place(w, x+0, y+3, z+1, Blocks.wool, 8);
        for(int dx=1; dx<3; dx++) place(w, x+dx, y+3, z+1, Blocks.stonebrick, 2);
        place(w, x+3, y+3, z+1, Blocks.stone_stairs, 2);
        place(w, x+4, y+3, z+1, Blocks.stonebrick, 2);
        place(w, x+5, y+3, z+1, Blocks.wool, 8);
        for(int dx=6; dx<8; dx++) place(w, x+dx, y+3, z+1, Blocks.stone, 0);
        place(w, x+8, y+3, z+1, Blocks.stone_brick_stairs, 2);
        place(w, x+9, y+3, z+1, Blocks.stone, 6);
        place(w, x+10, y+3, z+1, Blocks.wool, 8);
        place(w, x+11, y+3, z+1, Blocks.stone, 0);
        place(w, x+12, y+3, z+1, Blocks.stone_brick_stairs, 2);
        for(int dx=13; dx<15; dx++) place(w, x+dx, y+3, z+1, Blocks.stonebrick, 2);
        place(w, x+15, y+3, z+1, Blocks.wool, 8);
        place(w, x+16, y+3, z+1, Blocks.stone, 0);
        place(w, x+17, y+3, z+1, Blocks.stone_stairs, 2);
        place(w, x+18, y+3, z+1, Blocks.stone, 0);
        place(w, x+19, y+3, z+1, Blocks.stonebrick, 2);
        place(w, x+20, y+3, z+1, Blocks.wool, 8);
        for(int dx=0; dx<21; dx++) place(w, x+dx, y+8, z+1, Blocks.stone_brick_stairs, 6);
        for(int dx=0; dx<22; dx++) place(w, x+dx, y+9, z+1, legends_concrete, 8);
        for(int dx=0; dx<21; dx++) place(w, x+dx, y+10, z+1, Blocks.double_stone_slab, 5);
        place(w, x+21, y+10, z+1, Blocks.stone_slab, 5);
        place(w, x+0, y+0, z+2, Blocks.stonebrick, 1);
        place(w, x+1, y+0, z+2, Blocks.stone, 0);
        for(int dx=2; dx<11; dx++) place(w, x+dx, y+0, z+2, Blocks.stone, 6);
        for(int dx=11; dx<13; dx++) place(w, x+dx, y+0, z+2, Blocks.stone, 0);
        place(w, x+13, y+0, z+2, Blocks.stonebrick, 1);
        place(w, x+14, y+0, z+2, Blocks.stone, 0);
        place(w, x+15, y+0, z+2, Blocks.stone, 6);
        place(w, x+16, y+0, z+2, Blocks.stonebrick, 1);
        for(int dx=17; dx<19; dx++) place(w, x+dx, y+0, z+2, Blocks.stone, 6);
        place(w, x+19, y+0, z+2, Blocks.stone, 0);
        place(w, x+20, y+0, z+2, Blocks.stonebrick, 1);
        for(int dx=0; dx<3; dx++) place(w, x+dx, y+1, z+2, Blocks.stone, 0);
        place(w, x+3, y+1, z+2, Blocks.stonebrick, 1);
        place(w, x+4, y+1, z+2, Blocks.stone, 6);
        place(w, x+5, y+1, z+2, Blocks.stone, 0);
        place(w, x+6, y+1, z+2, Blocks.stonebrick, 1);
        place(w, x+7, y+1, z+2, Blocks.stone, 0);
        for(int dx=8; dx<11; dx++) place(w, x+dx, y+1, z+2, Blocks.stone, 6);
        for(int dx=11; dx<14; dx++) place(w, x+dx, y+1, z+2, Blocks.stone, 0);
        for(int dx=14; dx<17; dx++) place(w, x+dx, y+1, z+2, Blocks.stonebrick, 1);
        place(w, x+17, y+1, z+2, Blocks.stone, 0);
        place(w, x+18, y+1, z+2, Blocks.stonebrick, 2);
        for(int dx=19; dx<21; dx++) place(w, x+dx, y+1, z+2, Blocks.stone, 0);
        place(w, x+0, y+2, z+2, Blocks.stonebrick, 2);
        for(int dx=1; dx<3; dx++) place(w, x+dx, y+2, z+2, Blocks.stone, 0);
        place(w, x+3, y+2, z+2, Blocks.stone, 6);
        for(int dx=4; dx<6; dx++) place(w, x+dx, y+2, z+2, Blocks.stone, 0);
        for(int dx=6; dx<8; dx++) place(w, x+dx, y+2, z+2, Blocks.stonebrick, 1);
        place(w, x+8, y+2, z+2, Blocks.stone, 0);
        place(w, x+9, y+2, z+2, Blocks.stone, 6);
        for(int dx=10; dx<12; dx++) place(w, x+dx, y+2, z+2, Blocks.stone, 0);
        for(int dx=12; dx<15; dx++) place(w, x+dx, y+2, z+2, Blocks.stonebrick, 1);
        for(int dx=15; dx<18; dx++) place(w, x+dx, y+2, z+2, Blocks.stone, 0);
        place(w, x+18, y+2, z+2, Blocks.stone, 6);
        for(int dx=19; dx<21; dx++) place(w, x+dx, y+2, z+2, Blocks.stonebrick, 2);
        place(w, x+0, y+3, z+2, Blocks.stonebrick, 2);
        place(w, x+1, y+3, z+2, Blocks.stone, 6);
        place(w, x+2, y+3, z+2, Blocks.stonebrick, 2);
        place(w, x+3, y+3, z+2, Blocks.stone, 0);
        place(w, x+4, y+3, z+2, Blocks.stonebrick, 1);
        place(w, x+5, y+3, z+2, Blocks.stonebrick, 2);
        for(int dx=6; dx<10; dx++) place(w, x+dx, y+3, z+2, Blocks.stone, 0);
        place(w, x+10, y+3, z+2, Blocks.stonebrick, 2);
        place(w, x+11, y+3, z+2, Blocks.stone, 0);
        place(w, x+12, y+3, z+2, Blocks.stonebrick, 1);
        for(int dx=13; dx<15; dx++) place(w, x+dx, y+3, z+2, Blocks.stone, 0);
        for(int dx=15; dx<17; dx++) place(w, x+dx, y+3, z+2, Blocks.stonebrick, 2);
        place(w, x+17, y+3, z+2, Blocks.stone, 0);
        for(int dx=18; dx<21; dx++) place(w, x+dx, y+3, z+2, Blocks.stonebrick, 2);
        place(w, x+1, y+4, z+2, Blocks.wool, 8);
        place(w, x+2, y+4, z+2, Blocks.stonebrick, 2);
        for(int dx=3; dx<5; dx++) place(w, x+dx, y+4, z+2, Blocks.stone_brick_stairs, 2);
        place(w, x+5, y+4, z+2, Blocks.stonebrick, 2);
        place(w, x+6, y+4, z+2, Blocks.wool, 8);
        place(w, x+7, y+4, z+2, Blocks.stonebrick, 2);
        place(w, x+8, y+4, z+2, Blocks.stone_stairs, 2);
        place(w, x+9, y+4, z+2, Blocks.stone, 0);
        place(w, x+10, y+4, z+2, Blocks.wool, 8);
        place(w, x+11, y+4, z+2, Blocks.stonebrick, 2);
        place(w, x+12, y+4, z+2, Blocks.stone_brick_stairs, 2);
        place(w, x+13, y+4, z+2, Blocks.stonebrick, 2);
        place(w, x+14, y+4, z+2, Blocks.wool, 8);
        place(w, x+15, y+4, z+2, Blocks.stonebrick, 2);
        for(int dx=16; dx<18; dx++) place(w, x+dx, y+4, z+2, Blocks.stone_stairs, 2);
        place(w, x+18, y+4, z+2, Blocks.stonebrick, 2);
        place(w, x+19, y+4, z+2, Blocks.wool, 8);
        place(w, x+1, y+5, z+2, Blocks.wool, 8);
        place(w, x+2, y+5, z+2, Blocks.stone, 6);
        for(int dx=3; dx<5; dx++) place(w, x+dx, y+5, z+2, Blocks.stone_brick_stairs, 2);
        place(w, x+5, y+5, z+2, Blocks.stone, 6);
        place(w, x+6, y+5, z+2, Blocks.wool, 8);
        place(w, x+7, y+5, z+2, Blocks.stonebrick, 2);
        place(w, x+8, y+5, z+2, Blocks.stone_brick_stairs, 2);
        place(w, x+9, y+5, z+2, Blocks.stone, 0);
        place(w, x+10, y+5, z+2, Blocks.wool, 8);
        place(w, x+11, y+5, z+2, Blocks.stonebrick, 2);
        place(w, x+12, y+5, z+2, Blocks.stone_brick_stairs, 2);
        place(w, x+13, y+5, z+2, Blocks.stonebrick, 2);
        place(w, x+14, y+5, z+2, Blocks.wool, 8);
        place(w, x+15, y+5, z+2, Blocks.stone, 6);
        for(int dx=16; dx<18; dx++) place(w, x+dx, y+5, z+2, Blocks.stone_brick_stairs, 2);
        place(w, x+18, y+5, z+2, Blocks.stone, 6);
        place(w, x+19, y+5, z+2, Blocks.wool, 8);
        place(w, x+1, y+6, z+2, Blocks.wool, 8);
        place(w, x+2, y+6, z+2, Blocks.stone, 6);
        for(int dx=3; dx<5; dx++) place(w, x+dx, y+6, z+2, Blocks.stone_brick_stairs, 2);
        place(w, x+5, y+6, z+2, Blocks.stone, 6);
        place(w, x+6, y+6, z+2, Blocks.wool, 8);
        place(w, x+7, y+6, z+2, Blocks.stone, 6);
        place(w, x+8, y+6, z+2, Blocks.stone_brick_stairs, 2);
        place(w, x+9, y+6, z+2, Blocks.stone, 6);
        place(w, x+10, y+6, z+2, Blocks.wool, 8);
        place(w, x+11, y+6, z+2, Blocks.stone, 6);
        place(w, x+12, y+6, z+2, Blocks.stone_brick_stairs, 2);
        place(w, x+13, y+6, z+2, Blocks.stone, 6);
        place(w, x+14, y+6, z+2, Blocks.wool, 8);
        place(w, x+15, y+6, z+2, Blocks.stone, 6);
        for(int dx=16; dx<18; dx++) place(w, x+dx, y+6, z+2, Blocks.stone_brick_stairs, 2);
        place(w, x+18, y+6, z+2, Blocks.stone, 6);
        place(w, x+19, y+6, z+2, Blocks.wool, 8);
        place(w, x+1, y+7, z+2, Blocks.wool, 8);
        for(int dx=2; dx<6; dx++) place(w, x+dx, y+7, z+2, Blocks.stone, 6);
        place(w, x+6, y+7, z+2, Blocks.wool, 8);
        for(int dx=7; dx<10; dx++) place(w, x+dx, y+7, z+2, Blocks.stone, 6);
        place(w, x+10, y+7, z+2, Blocks.wool, 8);
        for(int dx=11; dx<14; dx++) place(w, x+dx, y+7, z+2, Blocks.stone, 6);
        place(w, x+14, y+7, z+2, Blocks.wool, 8);
        for(int dx=15; dx<19; dx++) place(w, x+dx, y+7, z+2, Blocks.stone, 6);
        place(w, x+19, y+7, z+2, Blocks.wool, 8);
        place(w, x+0, y+8, z+2, Blocks.stone_brick_stairs, 4);
        for(int dx=1; dx<20; dx++) place(w, x+dx, y+8, z+2, Blocks.stone, 6);
        place(w, x+20, y+8, z+2, Blocks.stone_brick_stairs, 5);
        place(w, x+0, y+9, z+2, legends_concrete, 8);
        for(int dx=1; dx<5; dx++) place(w, x+dx, y+9, z+2, Blocks.air, 0);
        for(int dx=5; dx<7; dx++) place(w, x+dx, y+9, z+2, Blocks.vine, 4);
        for(int dx=7; dx<19; dx++) place(w, x+dx, y+9, z+2, Blocks.air, 0);
        for(int dx=20; dx<22; dx++) place(w, x+dx, y+9, z+2, legends_concrete, 8);
        place(w, x+0, y+10, z+2, Blocks.double_stone_slab, 5);
        for(int dx=1; dx<20; dx++) place(w, x+dx, y+10, z+2, Blocks.double_stone_slab, 8);
        place(w, x+20, y+10, z+2, Blocks.double_stone_slab, 5);
        place(w, x+21, y+10, z+2, Blocks.stone_slab, 5);
        for(int dx=0; dx<2; dx++) place(w, x+dx, y+0, z+3, Blocks.stone, 0);
        for(int dx=2; dx<7; dx++) place(w, x+dx, y+0, z+3, Blocks.air, 0);
        for(int dx=7; dx<9; dx++) place(w, x+dx, y+0, z+3, Blocks.tallgrass, 2);
        for(int dx=9; dx<12; dx++) place(w, x+dx, y+0, z+3, Blocks.air, 0);
        place(w, x+12, y+0, z+3, Blocks.tallgrass, 1);
        for(int dx=13; dx<19; dx++) place(w, x+dx, y+0, z+3, Blocks.air, 0);
        place(w, x+19, y+0, z+3, Blocks.stone, 6);
        place(w, x+20, y+0, z+3, Blocks.stonebrick, 1);
        place(w, x+0, y+1, z+3, Blocks.stone_stairs, 0);
        place(w, x+1, y+1, z+3, Blocks.stonebrick, 1);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+1, z+3, Blocks.air, 0);
        place(w, x+19, y+1, z+3, Blocks.stone, 0);
        place(w, x+20, y+1, z+3, Blocks.stone_brick_stairs, 1);
        place(w, x+0, y+2, z+3, Blocks.stone_stairs, 0);
        place(w, x+1, y+2, z+3, Blocks.stone, 0);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+2, z+3, Blocks.air, 0);
        place(w, x+19, y+2, z+3, Blocks.stone, 0);
        place(w, x+20, y+2, z+3, Blocks.stone_brick_stairs, 1);
        for(int dx=0; dx<2; dx++) place(w, x+dx, y+3, z+3, Blocks.stonebrick, 2);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+3, z+3, Blocks.air, 0);
        place(w, x+19, y+3, z+3, Blocks.stonebrick, 2);
        place(w, x+20, y+3, z+3, Blocks.stone, 0);
        place(w, x+1, y+4, z+3, Blocks.stone, 6);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+4, z+3, Blocks.air, 0);
        place(w, x+19, y+4, z+3, Blocks.stonebrick, 2);
        place(w, x+1, y+5, z+3, Blocks.stone, 6);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+5, z+3, Blocks.air, 0);
        place(w, x+19, y+5, z+3, Blocks.stone, 6);
        place(w, x+1, y+6, z+3, Blocks.stone, 6);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+6, z+3, Blocks.air, 0);
        place(w, x+19, y+6, z+3, Blocks.stone, 6);
        place(w, x+1, y+7, z+3, Blocks.stone, 6);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+7, z+3, Blocks.air, 0);
        place(w, x+19, y+7, z+3, Blocks.stone, 6);
        place(w, x+0, y+8, z+3, Blocks.stone_brick_stairs, 4);
        place(w, x+1, y+8, z+3, Blocks.stone, 6);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+8, z+3, Blocks.air, 0);
        place(w, x+19, y+8, z+3, Blocks.stone, 6);
        place(w, x+20, y+8, z+3, Blocks.stone_brick_stairs, 5);
        place(w, x+0, y+9, z+3, legends_concrete, 8);
        for(int dx=1; dx<5; dx++) place(w, x+dx, y+9, z+3, Blocks.air, 0);
        for(int dx=5; dx<7; dx++) place(w, x+dx, y+9, z+3, Blocks.vine, 0);
        for(int dx=7; dx<19; dx++) place(w, x+dx, y+9, z+3, Blocks.air, 0);
        for(int dx=20; dx<22; dx++) place(w, x+dx, y+9, z+3, legends_concrete, 8);
        place(w, x+0, y+10, z+3, Blocks.double_stone_slab, 5);
        for(int dx=1; dx<20; dx++) place(w, x+dx, y+10, z+3, Blocks.double_stone_slab, 8);
        place(w, x+20, y+10, z+3, Blocks.double_stone_slab, 5);
        place(w, x+21, y+10, z+3, Blocks.stone_slab, 5);
        place(w, x+0, y+0, z+4, Blocks.stonebrick, 1);
        place(w, x+1, y+0, z+4, Blocks.stone, 6);
        for(int dx=2; dx<12; dx++) place(w, x+dx, y+0, z+4, Blocks.air, 0);
        place(w, x+12, y+0, z+4, Blocks.tallgrass, 2);
        for(int dx=13; dx<19; dx++) place(w, x+dx, y+0, z+4, Blocks.air, 0);
        place(w, x+19, y+0, z+4, Blocks.stone, 0);
        place(w, x+20, y+0, z+4, Blocks.stonebrick, 1);
        place(w, x+0, y+1, z+4, Blocks.stone_brick_stairs, 0);
        place(w, x+1, y+1, z+4, Blocks.stone, 0);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+1, z+4, Blocks.air, 0);
        place(w, x+19, y+1, z+4, Blocks.stone, 0);
        place(w, x+20, y+1, z+4, Blocks.stone_brick_stairs, 1);
        place(w, x+0, y+2, z+4, Blocks.stone_stairs, 0);
        place(w, x+1, y+2, z+4, Blocks.stone, 0);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+2, z+4, Blocks.air, 0);
        place(w, x+19, y+2, z+4, Blocks.stonebrick, 2);
        place(w, x+20, y+2, z+4, Blocks.stone_brick_stairs, 1);
        place(w, x+0, y+3, z+4, Blocks.stone_stairs, 0);
        place(w, x+1, y+3, z+4, Blocks.stonebrick, 2);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+3, z+4, Blocks.air, 0);
        place(w, x+19, y+3, z+4, Blocks.stone, 0);
        place(w, x+20, y+3, z+4, Blocks.stone_brick_stairs, 1);
        place(w, x+1, y+4, z+4, Blocks.stone_brick_stairs, 0);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+4, z+4, Blocks.air, 0);
        place(w, x+19, y+4, z+4, Blocks.stone_stairs, 1);
        place(w, x+1, y+5, z+4, Blocks.stone_brick_stairs, 0);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+5, z+4, Blocks.air, 0);
        place(w, x+19, y+5, z+4, Blocks.stone_brick_stairs, 1);
        place(w, x+1, y+6, z+4, Blocks.stone_brick_stairs, 0);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+6, z+4, Blocks.air, 0);
        place(w, x+19, y+6, z+4, Blocks.stone_brick_stairs, 1);
        place(w, x+1, y+7, z+4, Blocks.stone, 6);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+7, z+4, Blocks.air, 0);
        place(w, x+19, y+7, z+4, Blocks.stone, 6);
        place(w, x+0, y+8, z+4, Blocks.stone_brick_stairs, 4);
        place(w, x+1, y+8, z+4, Blocks.stone, 6);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+8, z+4, Blocks.air, 0);
        place(w, x+19, y+8, z+4, Blocks.stone, 6);
        place(w, x+20, y+8, z+4, Blocks.stone_brick_stairs, 5);
        place(w, x+21, y+8, z+4, Blocks.vine, 0);
        place(w, x+0, y+9, z+4, legends_concrete, 8);
        for(int dx=1; dx<5; dx++) place(w, x+dx, y+9, z+4, Blocks.air, 0);
        place(w, x+5, y+9, z+4, Blocks.vine, 0);
        for(int dx=6; dx<19; dx++) place(w, x+dx, y+9, z+4, Blocks.air, 0);
        for(int dx=20; dx<22; dx++) place(w, x+dx, y+9, z+4, legends_concrete, 8);
        place(w, x+0, y+10, z+4, Blocks.double_stone_slab, 5);
        for(int dx=1; dx<20; dx++) place(w, x+dx, y+10, z+4, Blocks.double_stone_slab, 8);
        place(w, x+20, y+10, z+4, Blocks.double_stone_slab, 5);
        place(w, x+21, y+10, z+4, Blocks.stone_slab, 5);
        place(w, x+0, y+0, z+5, Blocks.stonebrick, 1);
        place(w, x+1, y+0, z+5, Blocks.stone, 6);
        for(int dx=2; dx<8; dx++) place(w, x+dx, y+0, z+5, Blocks.air, 0);
        place(w, x+8, y+0, z+5, Blocks.tallgrass, 1);
        for(int dx=9; dx<19; dx++) place(w, x+dx, y+0, z+5, Blocks.air, 0);
        for(int dx=19; dx<21; dx++) place(w, x+dx, y+0, z+5, Blocks.stone, 6);
        place(w, x+0, y+1, z+5, Blocks.stone_stairs, 0);
        place(w, x+1, y+1, z+5, Blocks.stone, 0);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+1, z+5, Blocks.air, 0);
        place(w, x+19, y+1, z+5, Blocks.stone, 0);
        place(w, x+20, y+1, z+5, Blocks.stone_stairs, 1);
        place(w, x+0, y+2, z+5, Blocks.stone_brick_stairs, 0);
        place(w, x+1, y+2, z+5, Blocks.stone, 0);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+2, z+5, Blocks.air, 0);
        place(w, x+19, y+2, z+5, Blocks.stone, 0);
        place(w, x+20, y+2, z+5, Blocks.stone_stairs, 1);
        place(w, x+0, y+3, z+5, Blocks.stone_brick_stairs, 0);
        place(w, x+1, y+3, z+5, Blocks.stonebrick, 2);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+3, z+5, Blocks.air, 0);
        place(w, x+19, y+3, z+5, Blocks.stonebrick, 2);
        place(w, x+20, y+3, z+5, Blocks.stone_stairs, 1);
        place(w, x+1, y+4, z+5, Blocks.stone_brick_stairs, 0);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+4, z+5, Blocks.air, 0);
        place(w, x+19, y+4, z+5, Blocks.stone_brick_stairs, 1);
        place(w, x+1, y+5, z+5, Blocks.stone_brick_stairs, 0);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+5, z+5, Blocks.air, 0);
        place(w, x+19, y+5, z+5, Blocks.stone_brick_stairs, 1);
        place(w, x+1, y+6, z+5, Blocks.stone_brick_stairs, 0);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+6, z+5, Blocks.air, 0);
        place(w, x+19, y+6, z+5, Blocks.stone_brick_stairs, 1);
        place(w, x+1, y+7, z+5, Blocks.stone, 6);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+7, z+5, Blocks.air, 0);
        place(w, x+19, y+7, z+5, Blocks.stone, 6);
        place(w, x+0, y+8, z+5, Blocks.stone_brick_stairs, 4);
        place(w, x+1, y+8, z+5, Blocks.stone, 6);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+8, z+5, Blocks.air, 0);
        place(w, x+19, y+8, z+5, Blocks.stone, 6);
        place(w, x+20, y+8, z+5, Blocks.stone_brick_stairs, 5);
        place(w, x+0, y+9, z+5, legends_concrete, 8);
        for(int dx=1; dx<19; dx++) place(w, x+dx, y+9, z+5, Blocks.air, 0);
        for(int dx=20; dx<22; dx++) place(w, x+dx, y+9, z+5, legends_concrete, 8);
        place(w, x+0, y+10, z+5, Blocks.double_stone_slab, 5);
        for(int dx=1; dx<20; dx++) place(w, x+dx, y+10, z+5, Blocks.double_stone_slab, 8);
        place(w, x+20, y+10, z+5, Blocks.double_stone_slab, 5);
        place(w, x+21, y+10, z+5, Blocks.stone_slab, 5);
        place(w, x+0, y+0, z+6, Blocks.stonebrick, 1);
        place(w, x+1, y+0, z+6, Blocks.stone, 6);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+0, z+6, Blocks.air, 0);
        for(int dx=19; dx<21; dx++) place(w, x+dx, y+0, z+6, Blocks.stone, 6);
        place(w, x+0, y+1, z+6, Blocks.stone_brick_stairs, 0);
        place(w, x+1, y+1, z+6, Blocks.stonebrick, 1);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+1, z+6, Blocks.air, 0);
        place(w, x+19, y+1, z+6, Blocks.stone, 6);
        place(w, x+20, y+1, z+6, Blocks.stone_stairs, 1);
        place(w, x+0, y+2, z+6, Blocks.stone_stairs, 0);
        place(w, x+1, y+2, z+6, Blocks.stone, 0);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+2, z+6, Blocks.air, 0);
        place(w, x+19, y+2, z+6, Blocks.stonebrick, 1);
        place(w, x+20, y+2, z+6, Blocks.stone_stairs, 1);
        place(w, x+0, y+3, z+6, Blocks.stone_brick_stairs, 0);
        place(w, x+1, y+3, z+6, Blocks.stone, 0);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+3, z+6, Blocks.air, 0);
        place(w, x+19, y+3, z+6, Blocks.stonebrick, 2);
        place(w, x+20, y+3, z+6, Blocks.stone_stairs, 1);
        place(w, x+1, y+4, z+6, Blocks.stone_stairs, 0);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+4, z+6, Blocks.air, 0);
        place(w, x+19, y+4, z+6, Blocks.stone_brick_stairs, 1);
        place(w, x+1, y+5, z+6, Blocks.stone_brick_stairs, 0);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+5, z+6, Blocks.air, 0);
        place(w, x+19, y+5, z+6, Blocks.stone_brick_stairs, 1);
        place(w, x+1, y+6, z+6, Blocks.stone_brick_stairs, 0);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+6, z+6, Blocks.air, 0);
        place(w, x+19, y+6, z+6, Blocks.stone_brick_stairs, 1);
        place(w, x+1, y+7, z+6, Blocks.stone, 6);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+7, z+6, Blocks.air, 0);
        place(w, x+19, y+7, z+6, Blocks.stone, 6);
        place(w, x+0, y+8, z+6, Blocks.stone_brick_stairs, 4);
        place(w, x+1, y+8, z+6, Blocks.stone, 6);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+8, z+6, Blocks.air, 0);
        place(w, x+19, y+8, z+6, Blocks.stone, 6);
        place(w, x+20, y+8, z+6, Blocks.stone_brick_stairs, 5);
        place(w, x+0, y+9, z+6, legends_concrete, 8);
        for(int dx=1; dx<19; dx++) place(w, x+dx, y+9, z+6, Blocks.air, 0);
        for(int dx=20; dx<22; dx++) place(w, x+dx, y+9, z+6, legends_concrete, 8);
        place(w, x+0, y+10, z+6, Blocks.double_stone_slab, 5);
        for(int dx=1; dx<20; dx++) place(w, x+dx, y+10, z+6, Blocks.double_stone_slab, 8);
        place(w, x+20, y+10, z+6, Blocks.double_stone_slab, 5);
        place(w, x+21, y+10, z+6, Blocks.stone_slab, 5);
        for(int dx=0; dx<2; dx++) place(w, x+dx, y+0, z+7, Blocks.stone, 6);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+0, z+7, Blocks.air, 0);
        for(int dx=19; dx<21; dx++) place(w, x+dx, y+0, z+7, Blocks.stone, 6);
        place(w, x+0, y+1, z+7, Blocks.stone, 6);
        place(w, x+1, y+1, z+7, Blocks.stonebrick, 1);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+1, z+7, Blocks.air, 0);
        for(int dx=19; dx<21; dx++) place(w, x+dx, y+1, z+7, Blocks.stonebrick, 1);
        for(int dx=0; dx<2; dx++) place(w, x+dx, y+2, z+7, Blocks.stonebrick, 2);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+2, z+7, Blocks.air, 0);
        for(int dx=19; dx<21; dx++) place(w, x+dx, y+2, z+7, Blocks.stone, 0);
        place(w, x+0, y+3, z+7, Blocks.stone, 0);
        place(w, x+1, y+3, z+7, Blocks.stonebrick, 2);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+3, z+7, Blocks.air, 0);
        for(int dx=19; dx<21; dx++) place(w, x+dx, y+3, z+7, Blocks.stone, 0);
        place(w, x+1, y+4, z+7, Blocks.stonebrick, 2);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+4, z+7, Blocks.air, 0);
        place(w, x+19, y+4, z+7, Blocks.stonebrick, 2);
        place(w, x+1, y+5, z+7, Blocks.stonebrick, 2);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+5, z+7, Blocks.air, 0);
        place(w, x+19, y+5, z+7, Blocks.stone, 6);
        place(w, x+1, y+6, z+7, Blocks.stone, 6);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+6, z+7, Blocks.air, 0);
        place(w, x+19, y+6, z+7, Blocks.stone, 6);
        place(w, x+1, y+7, z+7, Blocks.stone, 6);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+7, z+7, Blocks.air, 0);
        place(w, x+19, y+7, z+7, Blocks.stone, 6);
        place(w, x+0, y+8, z+7, Blocks.stone_brick_stairs, 4);
        place(w, x+1, y+8, z+7, Blocks.stone, 6);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+8, z+7, Blocks.air, 0);
        place(w, x+19, y+8, z+7, Blocks.stone, 6);
        place(w, x+20, y+8, z+7, Blocks.stone_brick_stairs, 5);
        place(w, x+0, y+9, z+7, legends_concrete, 8);
        for(int dx=1; dx<19; dx++) place(w, x+dx, y+9, z+7, Blocks.air, 0);
        for(int dx=20; dx<22; dx++) place(w, x+dx, y+9, z+7, legends_concrete, 8);
        place(w, x+0, y+10, z+7, Blocks.double_stone_slab, 5);
        for(int dx=1; dx<20; dx++) place(w, x+dx, y+10, z+7, Blocks.double_stone_slab, 8);
        place(w, x+20, y+10, z+7, Blocks.double_stone_slab, 5);
        place(w, x+21, y+10, z+7, Blocks.stone_slab, 5);
        place(w, x+0, y+0, z+8, Blocks.wool, 8);
        place(w, x+1, y+0, z+8, Blocks.stone, 6);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+0, z+8, Blocks.air, 0);
        place(w, x+19, y+0, z+8, Blocks.stone, 6);
        place(w, x+20, y+0, z+8, Blocks.wool, 8);
        place(w, x+0, y+1, z+8, Blocks.wool, 8);
        place(w, x+1, y+1, z+8, Blocks.stone, 6);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+1, z+8, Blocks.air, 0);
        place(w, x+19, y+1, z+8, Blocks.stone, 6);
        place(w, x+20, y+1, z+8, Blocks.wool, 8);
        place(w, x+0, y+2, z+8, Blocks.wool, 8);
        place(w, x+1, y+2, z+8, Blocks.stonebrick, 1);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+2, z+8, Blocks.air, 0);
        place(w, x+19, y+2, z+8, Blocks.stone, 0);
        place(w, x+20, y+2, z+8, Blocks.wool, 8);
        place(w, x+0, y+3, z+8, Blocks.wool, 8);
        place(w, x+1, y+3, z+8, Blocks.stone, 0);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+3, z+8, Blocks.air, 0);
        place(w, x+19, y+3, z+8, Blocks.stone, 0);
        place(w, x+20, y+3, z+8, Blocks.wool, 8);
        place(w, x+1, y+4, z+8, Blocks.wool, 8);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+4, z+8, Blocks.air, 0);
        place(w, x+19, y+4, z+8, Blocks.wool, 8);
        place(w, x+1, y+5, z+8, Blocks.wool, 8);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+5, z+8, Blocks.air, 0);
        place(w, x+19, y+5, z+8, Blocks.wool, 8);
        place(w, x+1, y+6, z+8, Blocks.wool, 8);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+6, z+8, Blocks.air, 0);
        place(w, x+19, y+6, z+8, Blocks.wool, 8);
        place(w, x+1, y+7, z+8, Blocks.wool, 8);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+7, z+8, Blocks.air, 0);
        place(w, x+19, y+7, z+8, Blocks.wool, 8);
        place(w, x+0, y+8, z+8, Blocks.stone_brick_stairs, 4);
        place(w, x+1, y+8, z+8, Blocks.stone, 6);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+8, z+8, Blocks.air, 0);
        place(w, x+19, y+8, z+8, Blocks.stone, 6);
        place(w, x+20, y+8, z+8, Blocks.stone_brick_stairs, 5);
        place(w, x+0, y+9, z+8, legends_concrete, 8);
        for(int dx=1; dx<19; dx++) place(w, x+dx, y+9, z+8, Blocks.air, 0);
        for(int dx=20; dx<22; dx++) place(w, x+dx, y+9, z+8, legends_concrete, 8);
        place(w, x+0, y+10, z+8, Blocks.double_stone_slab, 5);
        for(int dx=1; dx<20; dx++) place(w, x+dx, y+10, z+8, Blocks.double_stone_slab, 8);
        place(w, x+20, y+10, z+8, Blocks.double_stone_slab, 5);
        place(w, x+21, y+10, z+8, Blocks.stone_slab, 5);
        place(w, x+1, y+0, z+9, Blocks.wool, 8);
        place(w, x+2, y+0, z+9, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+0, z+9, Blocks.air, 0);
        place(w, x+18, y+0, z+9, Blocks.stone, 6);
        place(w, x+19, y+0, z+9, Blocks.wool, 8);
        place(w, x+1, y+1, z+9, Blocks.wool, 8);
        place(w, x+2, y+1, z+9, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+1, z+9, Blocks.air, 0);
        place(w, x+18, y+1, z+9, Blocks.stone, 6);
        place(w, x+19, y+1, z+9, Blocks.wool, 8);
        place(w, x+1, y+2, z+9, Blocks.wool, 8);
        place(w, x+2, y+2, z+9, Blocks.stone, 0);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+2, z+9, Blocks.air, 0);
        place(w, x+18, y+2, z+9, Blocks.stonebrick, 2);
        place(w, x+19, y+2, z+9, Blocks.wool, 8);
        place(w, x+1, y+3, z+9, Blocks.wool, 8);
        place(w, x+2, y+3, z+9, Blocks.stonebrick, 2);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+3, z+9, Blocks.air, 0);
        place(w, x+18, y+3, z+9, Blocks.stonebrick, 2);
        place(w, x+19, y+3, z+9, Blocks.wool, 8);
        place(w, x+2, y+4, z+9, Blocks.wool, 8);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+4, z+9, Blocks.air, 0);
        place(w, x+18, y+4, z+9, Blocks.wool, 8);
        place(w, x+2, y+5, z+9, Blocks.wool, 8);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+5, z+9, Blocks.air, 0);
        place(w, x+18, y+5, z+9, Blocks.wool, 8);
        place(w, x+2, y+6, z+9, Blocks.wool, 8);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+6, z+9, Blocks.air, 0);
        place(w, x+18, y+6, z+9, Blocks.wool, 8);
        place(w, x+2, y+7, z+9, Blocks.wool, 8);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+7, z+9, Blocks.air, 0);
        place(w, x+18, y+7, z+9, Blocks.wool, 8);
        place(w, x+0, y+8, z+9, Blocks.stone_brick_stairs, 7);
        place(w, x+1, y+8, z+9, Blocks.stone_brick_stairs, 4);
        place(w, x+2, y+8, z+9, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+8, z+9, Blocks.air, 0);
        place(w, x+18, y+8, z+9, Blocks.stone, 6);
        place(w, x+19, y+8, z+9, Blocks.stone_brick_stairs, 5);
        place(w, x+20, y+8, z+9, Blocks.stone_brick_stairs, 7);
        for(int dx=0; dx<2; dx++) place(w, x+dx, y+9, z+9, legends_concrete, 8);
        for(int dx=3; dx<19; dx++) place(w, x+dx, y+9, z+9, Blocks.air, 0);
        for(int dx=19; dx<22; dx++) place(w, x+dx, y+9, z+9, legends_concrete, 8);
        place(w, x+0, y+10, z+9, Blocks.stone_slab, 5);
        place(w, x+1, y+10, z+9, Blocks.double_stone_slab, 5);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+10, z+9, Blocks.double_stone_slab, 8);
        place(w, x+19, y+10, z+9, Blocks.double_stone_slab, 5);
        for(int dx=20; dx<22; dx++) place(w, x+dx, y+10, z+9, Blocks.stone_slab, 5);
        for(int dx=1; dx<3; dx++) place(w, x+dx, y+0, z+10, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+0, z+10, Blocks.air, 0);
        for(int dx=18; dx<20; dx++) place(w, x+dx, y+0, z+10, Blocks.stone, 6);
        for(int dx=1; dx<3; dx++) place(w, x+dx, y+1, z+10, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+1, z+10, Blocks.air, 0);
        for(int dx=18; dx<20; dx++) place(w, x+dx, y+1, z+10, Blocks.stone, 0);
        place(w, x+1, y+2, z+10, Blocks.stonebrick, 1);
        place(w, x+2, y+2, z+10, Blocks.stone, 0);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+2, z+10, Blocks.air, 0);
        place(w, x+18, y+2, z+10, Blocks.stone, 0);
        place(w, x+19, y+2, z+10, Blocks.stonebrick, 2);
        place(w, x+1, y+3, z+10, Blocks.stone, 0);
        place(w, x+2, y+3, z+10, Blocks.stonebrick, 2);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+3, z+10, Blocks.air, 0);
        for(int dx=18; dx<20; dx++) place(w, x+dx, y+3, z+10, Blocks.stone, 0);
        place(w, x+2, y+4, z+10, Blocks.stonebrick, 2);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+4, z+10, Blocks.air, 0);
        place(w, x+18, y+4, z+10, Blocks.stonebrick, 2);
        place(w, x+2, y+5, z+10, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+5, z+10, Blocks.air, 0);
        place(w, x+18, y+5, z+10, Blocks.stone, 6);
        place(w, x+2, y+6, z+10, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+6, z+10, Blocks.air, 0);
        place(w, x+18, y+6, z+10, Blocks.stone, 6);
        place(w, x+2, y+7, z+10, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+7, z+10, Blocks.air, 0);
        place(w, x+18, y+7, z+10, Blocks.stone, 6);
        place(w, x+1, y+8, z+10, Blocks.stone_brick_stairs, 4);
        place(w, x+2, y+8, z+10, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+8, z+10, Blocks.air, 0);
        place(w, x+18, y+8, z+10, Blocks.stone, 6);
        place(w, x+19, y+8, z+10, Blocks.stone_brick_stairs, 5);
        for(int dx=0; dx<2; dx++) place(w, x+dx, y+9, z+10, legends_concrete, 8);
        for(int dx=3; dx<19; dx++) place(w, x+dx, y+9, z+10, Blocks.air, 0);
        for(int dx=19; dx<21; dx++) place(w, x+dx, y+9, z+10, legends_concrete, 8);
        place(w, x+21, y+9, z+10, Blocks.stone_button, 1);
        place(w, x+0, y+10, z+10, Blocks.stone_slab, 5);
        place(w, x+1, y+10, z+10, Blocks.double_stone_slab, 5);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+10, z+10, Blocks.double_stone_slab, 8);
        place(w, x+19, y+10, z+10, Blocks.double_stone_slab, 5);
        place(w, x+20, y+10, z+10, Blocks.stone_slab, 5);
        for(int dx=1; dx<3; dx++) place(w, x+dx, y+0, z+11, Blocks.stonebrick, 1);
        for(int dx=3; dx<9; dx++) place(w, x+dx, y+0, z+11, Blocks.air, 0);
        place(w, x+9, y+0, z+11, Blocks.tallgrass, 1);
        for(int dx=10; dx<18; dx++) place(w, x+dx, y+0, z+11, Blocks.air, 0);
        place(w, x+18, y+0, z+11, Blocks.stone, 6);
        place(w, x+19, y+0, z+11, Blocks.stonebrick, 1);
        place(w, x+1, y+1, z+11, Blocks.stone_brick_stairs, 0);
        place(w, x+2, y+1, z+11, Blocks.stonebrick, 1);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+1, z+11, Blocks.air, 0);
        place(w, x+18, y+1, z+11, Blocks.stone, 0);
        place(w, x+19, y+1, z+11, Blocks.stone_stairs, 1);
        place(w, x+1, y+2, z+11, Blocks.stone_brick_stairs, 0);
        place(w, x+2, y+2, z+11, Blocks.stone, 0);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+2, z+11, Blocks.air, 0);
        place(w, x+18, y+2, z+11, Blocks.stonebrick, 2);
        place(w, x+19, y+2, z+11, Blocks.stone_stairs, 1);
        place(w, x+1, y+3, z+11, Blocks.stone_brick_stairs, 0);
        place(w, x+2, y+3, z+11, Blocks.stone, 0);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+3, z+11, Blocks.air, 0);
        place(w, x+18, y+3, z+11, Blocks.stonebrick, 2);
        place(w, x+19, y+3, z+11, Blocks.stone_stairs, 1);
        place(w, x+2, y+4, z+11, Blocks.stone_brick_stairs, 0);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+4, z+11, Blocks.air, 0);
        place(w, x+18, y+4, z+11, Blocks.stone_brick_stairs, 1);
        place(w, x+2, y+5, z+11, Blocks.stone_brick_stairs, 0);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+5, z+11, Blocks.air, 0);
        place(w, x+18, y+5, z+11, Blocks.stone_brick_stairs, 1);
        place(w, x+2, y+6, z+11, Blocks.stone_brick_stairs, 0);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+6, z+11, Blocks.air, 0);
        place(w, x+18, y+6, z+11, Blocks.stone_brick_stairs, 1);
        place(w, x+2, y+7, z+11, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+7, z+11, Blocks.air, 0);
        place(w, x+18, y+7, z+11, Blocks.stone, 6);
        place(w, x+1, y+8, z+11, Blocks.stone_brick_stairs, 4);
        place(w, x+2, y+8, z+11, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+8, z+11, Blocks.air, 0);
        place(w, x+18, y+8, z+11, Blocks.stone, 6);
        place(w, x+19, y+8, z+11, Blocks.stone_brick_stairs, 5);
        for(int dx=0; dx<2; dx++) place(w, x+dx, y+9, z+11, legends_concrete, 8);
        for(int dx=3; dx<19; dx++) place(w, x+dx, y+9, z+11, Blocks.air, 0);
        for(int dx=19; dx<21; dx++) place(w, x+dx, y+9, z+11, legends_concrete, 8);
        place(w, x+0, y+10, z+11, Blocks.stone_slab, 5);
        place(w, x+1, y+10, z+11, Blocks.double_stone_slab, 5);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+10, z+11, Blocks.double_stone_slab, 8);
        place(w, x+19, y+10, z+11, Blocks.double_stone_slab, 5);
        place(w, x+20, y+10, z+11, Blocks.stone_slab, 5);
        place(w, x+1, y+0, z+12, Blocks.stonebrick, 1);
        place(w, x+2, y+0, z+12, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+0, z+12, Blocks.air, 0);
        place(w, x+18, y+0, z+12, Blocks.stone, 6);
        place(w, x+19, y+0, z+12, Blocks.stonebrick, 1);
        place(w, x+1, y+1, z+12, Blocks.stone_stairs, 0);
        place(w, x+2, y+1, z+12, Blocks.stone, 0);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+1, z+12, Blocks.air, 0);
        place(w, x+18, y+1, z+12, Blocks.stone, 0);
        place(w, x+19, y+1, z+12, Blocks.stone_stairs, 1);
        place(w, x+1, y+2, z+12, Blocks.stone_brick_stairs, 0);
        place(w, x+2, y+2, z+12, Blocks.stone, 0);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+2, z+12, Blocks.air, 0);
        place(w, x+18, y+2, z+12, Blocks.stonebrick, 2);
        place(w, x+19, y+2, z+12, Blocks.stone_stairs, 1);
        place(w, x+1, y+3, z+12, Blocks.stone_stairs, 0);
        place(w, x+2, y+3, z+12, Blocks.stone, 0);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+3, z+12, Blocks.air, 0);
        place(w, x+18, y+3, z+12, Blocks.stonebrick, 2);
        place(w, x+19, y+3, z+12, Blocks.stone_brick_stairs, 1);
        place(w, x+2, y+4, z+12, Blocks.stone_stairs, 0);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+4, z+12, Blocks.air, 0);
        place(w, x+18, y+4, z+12, Blocks.stone_brick_stairs, 1);
        place(w, x+2, y+5, z+12, Blocks.stone_stairs, 0);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+5, z+12, Blocks.air, 0);
        place(w, x+18, y+5, z+12, Blocks.stone_brick_stairs, 1);
        place(w, x+2, y+6, z+12, Blocks.stone_brick_stairs, 0);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+6, z+12, Blocks.air, 0);
        place(w, x+18, y+6, z+12, Blocks.stone_brick_stairs, 1);
        place(w, x+2, y+7, z+12, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+7, z+12, Blocks.air, 0);
        place(w, x+18, y+7, z+12, Blocks.stone, 6);
        place(w, x+1, y+8, z+12, Blocks.stone_brick_stairs, 4);
        place(w, x+2, y+8, z+12, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+8, z+12, Blocks.air, 0);
        place(w, x+18, y+8, z+12, Blocks.stone, 6);
        place(w, x+19, y+8, z+12, Blocks.stone_brick_stairs, 5);
        for(int dx=0; dx<2; dx++) place(w, x+dx, y+9, z+12, legends_concrete, 8);
        for(int dx=3; dx<19; dx++) place(w, x+dx, y+9, z+12, Blocks.air, 0);
        for(int dx=19; dx<21; dx++) place(w, x+dx, y+9, z+12, legends_concrete, 8);
        place(w, x+0, y+10, z+12, Blocks.stone_slab, 5);
        place(w, x+1, y+10, z+12, Blocks.double_stone_slab, 5);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+10, z+12, Blocks.double_stone_slab, 8);
        place(w, x+19, y+10, z+12, Blocks.double_stone_slab, 5);
        place(w, x+20, y+10, z+12, Blocks.stone_slab, 5);
        place(w, x+1, y+0, z+13, Blocks.stone, 6);
        place(w, x+2, y+0, z+13, Blocks.stonebrick, 1);
        for(int dx=3; dx<10; dx++) place(w, x+dx, y+0, z+13, Blocks.air, 0);
        place(w, x+10, y+0, z+13, Blocks.tallgrass, 2);
        for(int dx=11; dx<18; dx++) place(w, x+dx, y+0, z+13, Blocks.air, 0);
        place(w, x+18, y+0, z+13, Blocks.stone, 6);
        place(w, x+19, y+0, z+13, Blocks.stonebrick, 1);
        place(w, x+1, y+1, z+13, Blocks.stone_stairs, 0);
        place(w, x+2, y+1, z+13, Blocks.stonebrick, 1);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+1, z+13, Blocks.air, 0);
        place(w, x+18, y+1, z+13, Blocks.stone, 0);
        place(w, x+19, y+1, z+13, Blocks.stone_brick_stairs, 1);
        place(w, x+1, y+2, z+13, Blocks.stone_stairs, 0);
        place(w, x+2, y+2, z+13, Blocks.stone, 0);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+2, z+13, Blocks.air, 0);
        place(w, x+18, y+2, z+13, Blocks.stonebrick, 2);
        place(w, x+19, y+2, z+13, Blocks.stone_stairs, 1);
        place(w, x+1, y+3, z+13, Blocks.stone_brick_stairs, 0);
        place(w, x+2, y+3, z+13, Blocks.stonebrick, 2);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+3, z+13, Blocks.air, 0);
        place(w, x+18, y+3, z+13, Blocks.stonebrick, 2);
        place(w, x+19, y+3, z+13, Blocks.stone_brick_stairs, 1);
        place(w, x+2, y+4, z+13, Blocks.stone_stairs, 0);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+4, z+13, Blocks.air, 0);
        place(w, x+18, y+4, z+13, Blocks.stone_brick_stairs, 1);
        place(w, x+2, y+5, z+13, Blocks.stone_brick_stairs, 0);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+5, z+13, Blocks.air, 0);
        place(w, x+18, y+5, z+13, Blocks.stone_brick_stairs, 1);
        place(w, x+2, y+6, z+13, Blocks.stone_brick_stairs, 0);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+6, z+13, Blocks.air, 0);
        place(w, x+18, y+6, z+13, Blocks.stone_brick_stairs, 1);
        place(w, x+2, y+7, z+13, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+7, z+13, Blocks.air, 0);
        place(w, x+18, y+7, z+13, Blocks.stone, 6);
        place(w, x+1, y+8, z+13, Blocks.stone_brick_stairs, 4);
        place(w, x+2, y+8, z+13, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+8, z+13, Blocks.air, 0);
        place(w, x+18, y+8, z+13, Blocks.stone, 6);
        place(w, x+19, y+8, z+13, Blocks.stone_brick_stairs, 5);
        for(int dx=0; dx<2; dx++) place(w, x+dx, y+9, z+13, legends_concrete, 8);
        for(int dx=3; dx<19; dx++) place(w, x+dx, y+9, z+13, Blocks.air, 0);
        for(int dx=19; dx<21; dx++) place(w, x+dx, y+9, z+13, legends_concrete, 8);
        place(w, x+21, y+9, z+13, Blocks.stone_button, 1);
        place(w, x+0, y+10, z+13, Blocks.stone_slab, 5);
        place(w, x+1, y+10, z+13, Blocks.double_stone_slab, 5);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+10, z+13, Blocks.double_stone_slab, 8);
        place(w, x+19, y+10, z+13, Blocks.double_stone_slab, 5);
        place(w, x+20, y+10, z+13, Blocks.stone_slab, 5);
        place(w, x+1, y+0, z+14, Blocks.stone, 6);
        place(w, x+2, y+0, z+14, Blocks.stonebrick, 1);
        for(int dx=3; dx<11; dx++) place(w, x+dx, y+0, z+14, Blocks.air, 0);
        place(w, x+11, y+0, z+14, Blocks.tallgrass, 1);
        for(int dx=12; dx<18; dx++) place(w, x+dx, y+0, z+14, Blocks.air, 0);
        for(int dx=18; dx<20; dx++) place(w, x+dx, y+0, z+14, Blocks.stone, 6);
        for(int dx=1; dx<3; dx++) place(w, x+dx, y+1, z+14, Blocks.stone, 0);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+1, z+14, Blocks.air, 0);
        for(int dx=18; dx<20; dx++) place(w, x+dx, y+1, z+14, Blocks.stone, 0);
        place(w, x+1, y+2, z+14, Blocks.stone, 0);
        place(w, x+2, y+2, z+14, Blocks.stonebrick, 2);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+2, z+14, Blocks.air, 0);
        place(w, x+18, y+2, z+14, Blocks.stonebrick, 2);
        place(w, x+19, y+2, z+14, Blocks.stone, 0);
        for(int dx=1; dx<3; dx++) place(w, x+dx, y+3, z+14, Blocks.stonebrick, 2);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+3, z+14, Blocks.air, 0);
        for(int dx=18; dx<20; dx++) place(w, x+dx, y+3, z+14, Blocks.stonebrick, 2);
        place(w, x+2, y+4, z+14, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+4, z+14, Blocks.air, 0);
        place(w, x+18, y+4, z+14, Blocks.stone, 0);
        place(w, x+2, y+5, z+14, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+5, z+14, Blocks.air, 0);
        place(w, x+18, y+5, z+14, Blocks.stonebrick, 2);
        place(w, x+2, y+6, z+14, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+6, z+14, Blocks.air, 0);
        place(w, x+18, y+6, z+14, Blocks.stone, 6);
        place(w, x+2, y+7, z+14, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+7, z+14, Blocks.air, 0);
        place(w, x+18, y+7, z+14, Blocks.stone, 6);
        place(w, x+1, y+8, z+14, Blocks.stone_brick_stairs, 4);
        place(w, x+2, y+8, z+14, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+8, z+14, Blocks.air, 0);
        place(w, x+18, y+8, z+14, Blocks.stone, 6);
        place(w, x+19, y+8, z+14, Blocks.stone_brick_stairs, 5);
        for(int dx=0; dx<2; dx++) place(w, x+dx, y+9, z+14, legends_concrete, 8);
        for(int dx=3; dx<19; dx++) place(w, x+dx, y+9, z+14, Blocks.air, 0);
        for(int dx=19; dx<21; dx++) place(w, x+dx, y+9, z+14, legends_concrete, 8);
        place(w, x+0, y+10, z+14, Blocks.stone_slab, 5);
        place(w, x+1, y+10, z+14, Blocks.double_stone_slab, 5);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+10, z+14, Blocks.double_stone_slab, 8);
        place(w, x+19, y+10, z+14, Blocks.double_stone_slab, 5);
        place(w, x+20, y+10, z+14, Blocks.stone_slab, 5);
        place(w, x+1, y+0, z+15, Blocks.wool, 8);
        place(w, x+2, y+0, z+15, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+0, z+15, Blocks.air, 0);
        place(w, x+18, y+0, z+15, Blocks.stone, 6);
        place(w, x+19, y+0, z+15, Blocks.wool, 8);
        place(w, x+21, y+0, z+15, Blocks.tallgrass, 1);
        place(w, x+1, y+1, z+15, Blocks.wool, 8);
        place(w, x+2, y+1, z+15, Blocks.stonebrick, 1);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+1, z+15, Blocks.air, 0);
        place(w, x+18, y+1, z+15, Blocks.stone, 0);
        place(w, x+19, y+1, z+15, Blocks.wool, 8);
        place(w, x+1, y+2, z+15, Blocks.wool, 8);
        place(w, x+2, y+2, z+15, Blocks.stonebrick, 2);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+2, z+15, Blocks.air, 0);
        place(w, x+18, y+2, z+15, Blocks.stone, 0);
        place(w, x+19, y+2, z+15, Blocks.wool, 8);
        place(w, x+1, y+3, z+15, Blocks.wool, 8);
        place(w, x+2, y+3, z+15, Blocks.stonebrick, 2);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+3, z+15, Blocks.air, 0);
        place(w, x+18, y+3, z+15, Blocks.stone, 0);
        place(w, x+19, y+3, z+15, Blocks.wool, 8);
        place(w, x+2, y+4, z+15, Blocks.wool, 8);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+4, z+15, Blocks.air, 0);
        place(w, x+18, y+4, z+15, Blocks.wool, 8);
        place(w, x+2, y+5, z+15, Blocks.wool, 8);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+5, z+15, Blocks.air, 0);
        place(w, x+18, y+5, z+15, Blocks.wool, 8);
        place(w, x+2, y+6, z+15, Blocks.wool, 8);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+6, z+15, Blocks.air, 0);
        place(w, x+18, y+6, z+15, Blocks.wool, 8);
        place(w, x+2, y+7, z+15, Blocks.wool, 8);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+7, z+15, Blocks.air, 0);
        place(w, x+18, y+7, z+15, Blocks.wool, 8);
        place(w, x+1, y+8, z+15, Blocks.stone_brick_stairs, 4);
        place(w, x+2, y+8, z+15, Blocks.stone, 6);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+8, z+15, Blocks.air, 0);
        place(w, x+18, y+8, z+15, Blocks.stone, 6);
        place(w, x+19, y+8, z+15, Blocks.stone_brick_stairs, 5);
        for(int dx=0; dx<2; dx++) place(w, x+dx, y+9, z+15, legends_concrete, 8);
        for(int dx=3; dx<19; dx++) place(w, x+dx, y+9, z+15, Blocks.air, 0);
        for(int dx=19; dx<21; dx++) place(w, x+dx, y+9, z+15, legends_concrete, 8);
        place(w, x+0, y+10, z+15, Blocks.stone_slab, 5);
        place(w, x+1, y+10, z+15, Blocks.double_stone_slab, 5);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+10, z+15, Blocks.double_stone_slab, 8);
        place(w, x+19, y+10, z+15, Blocks.double_stone_slab, 5);
        place(w, x+20, y+10, z+15, Blocks.stone_slab, 5);
        place(w, x+2, y+0, z+16, Blocks.wool, 8);
        place(w, x+3, y+0, z+16, Blocks.stone, 6);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+0, z+16, Blocks.air, 0);
        place(w, x+17, y+0, z+16, Blocks.stone, 0);
        place(w, x+18, y+0, z+16, Blocks.wool, 8);
        place(w, x+2, y+1, z+16, Blocks.wool, 8);
        place(w, x+3, y+1, z+16, Blocks.stone, 6);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+1, z+16, Blocks.air, 0);
        place(w, x+17, y+1, z+16, Blocks.stonebrick, 1);
        place(w, x+18, y+1, z+16, Blocks.wool, 8);
        place(w, x+2, y+2, z+16, Blocks.wool, 8);
        place(w, x+3, y+2, z+16, Blocks.stone, 0);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+2, z+16, Blocks.air, 0);
        place(w, x+17, y+2, z+16, Blocks.stonebrick, 1);
        place(w, x+18, y+2, z+16, Blocks.wool, 8);
        place(w, x+2, y+3, z+16, Blocks.wool, 8);
        place(w, x+3, y+3, z+16, Blocks.stone, 0);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+3, z+16, Blocks.air, 0);
        place(w, x+17, y+3, z+16, Blocks.stone, 0);
        place(w, x+18, y+3, z+16, Blocks.wool, 8);
        place(w, x+3, y+4, z+16, Blocks.wool, 8);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+4, z+16, Blocks.air, 0);
        place(w, x+17, y+4, z+16, Blocks.wool, 8);
        place(w, x+3, y+5, z+16, Blocks.wool, 8);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+5, z+16, Blocks.air, 0);
        place(w, x+17, y+5, z+16, Blocks.wool, 8);
        place(w, x+3, y+6, z+16, Blocks.wool, 8);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+6, z+16, Blocks.air, 0);
        place(w, x+17, y+6, z+16, Blocks.wool, 8);
        place(w, x+3, y+7, z+16, Blocks.wool, 8);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+7, z+16, Blocks.air, 0);
        place(w, x+17, y+7, z+16, Blocks.wool, 8);
        place(w, x+1, y+8, z+16, Blocks.stone_brick_stairs, 7);
        place(w, x+2, y+8, z+16, Blocks.stone_brick_stairs, 4);
        place(w, x+3, y+8, z+16, Blocks.stone, 6);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+8, z+16, Blocks.air, 0);
        place(w, x+17, y+8, z+16, Blocks.stone, 6);
        place(w, x+18, y+8, z+16, Blocks.stone_brick_stairs, 5);
        place(w, x+19, y+8, z+16, Blocks.stone_brick_stairs, 7);
        for(int dx=0; dx<3; dx++) place(w, x+dx, y+9, z+16, legends_concrete, 8);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+9, z+16, Blocks.air, 0);
        for(int dx=18; dx<21; dx++) place(w, x+dx, y+9, z+16, legends_concrete, 8);
        place(w, x+21, y+9, z+16, Blocks.stone_button, 1);
        for(int dx=0; dx<2; dx++) place(w, x+dx, y+10, z+16, Blocks.stone_slab, 5);
        place(w, x+2, y+10, z+16, Blocks.double_stone_slab, 5);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+10, z+16, Blocks.double_stone_slab, 8);
        place(w, x+18, y+10, z+16, Blocks.double_stone_slab, 5);
        for(int dx=19; dx<21; dx++) place(w, x+dx, y+10, z+16, Blocks.stone_slab, 5);
        for(int dx=2; dx<4; dx++) place(w, x+dx, y+0, z+17, Blocks.stone, 6);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+0, z+17, Blocks.air, 0);
        for(int dx=17; dx<19; dx++) place(w, x+dx, y+0, z+17, Blocks.stone, 0);
        place(w, x+2, y+1, z+17, Blocks.stonebrick, 1);
        place(w, x+3, y+1, z+17, Blocks.stone, 6);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+1, z+17, Blocks.air, 0);
        for(int dx=17; dx<19; dx++) place(w, x+dx, y+1, z+17, Blocks.stone, 0);
        for(int dx=2; dx<4; dx++) place(w, x+dx, y+2, z+17, Blocks.stone, 0);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+2, z+17, Blocks.air, 0);
        for(int dx=17; dx<19; dx++) place(w, x+dx, y+2, z+17, Blocks.stone, 0);
        for(int dx=2; dx<4; dx++) place(w, x+dx, y+3, z+17, Blocks.stonebrick, 2);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+3, z+17, Blocks.air, 0);
        place(w, x+17, y+3, z+17, Blocks.stonebrick, 2);
        place(w, x+18, y+3, z+17, Blocks.stone, 0);
        place(w, x+3, y+4, z+17, Blocks.stone, 0);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+4, z+17, Blocks.air, 0);
        place(w, x+17, y+4, z+17, Blocks.stone, 0);
        place(w, x+3, y+5, z+17, Blocks.stone, 6);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+5, z+17, Blocks.air, 0);
        place(w, x+17, y+5, z+17, Blocks.stonebrick, 2);
        place(w, x+3, y+6, z+17, Blocks.stone, 6);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+6, z+17, Blocks.air, 0);
        place(w, x+17, y+6, z+17, Blocks.stone, 6);
        place(w, x+3, y+7, z+17, Blocks.stone, 6);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+7, z+17, Blocks.air, 0);
        place(w, x+17, y+7, z+17, Blocks.stone, 6);
        place(w, x+2, y+8, z+17, Blocks.stone_brick_stairs, 4);
        place(w, x+3, y+8, z+17, Blocks.stone, 6);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+8, z+17, Blocks.air, 0);
        place(w, x+17, y+8, z+17, Blocks.stone, 6);
        place(w, x+18, y+8, z+17, Blocks.stone_brick_stairs, 5);
        place(w, x+0, y+9, z+17, Blocks.stone_button, 2);
        for(int dx=1; dx<3; dx++) place(w, x+dx, y+9, z+17, legends_concrete, 8);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+9, z+17, Blocks.air, 0);
        for(int dx=18; dx<20; dx++) place(w, x+dx, y+9, z+17, legends_concrete, 8);
        place(w, x+20, y+9, z+17, Blocks.stone_button, 1);
        place(w, x+1, y+10, z+17, Blocks.stone_slab, 5);
        place(w, x+2, y+10, z+17, Blocks.double_stone_slab, 5);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+10, z+17, Blocks.double_stone_slab, 8);
        place(w, x+18, y+10, z+17, Blocks.double_stone_slab, 5);
        place(w, x+19, y+10, z+17, Blocks.stone_slab, 5);
        for(int dx=2; dx<4; dx++) place(w, x+dx, y+0, z+18, Blocks.stone, 6);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+0, z+18, Blocks.air, 0);
        for(int dx=17; dx<19; dx++) place(w, x+dx, y+0, z+18, Blocks.stone, 0);
        place(w, x+2, y+1, z+18, Blocks.stone_stairs, 0);
        place(w, x+3, y+1, z+18, Blocks.stone, 0);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+1, z+18, Blocks.air, 0);
        place(w, x+17, y+1, z+18, Blocks.stonebrick, 1);
        place(w, x+18, y+1, z+18, Blocks.stone_brick_stairs, 1);
        place(w, x+2, y+2, z+18, Blocks.stone_brick_stairs, 0);
        place(w, x+3, y+2, z+18, Blocks.stone, 0);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+2, z+18, Blocks.air, 0);
        place(w, x+17, y+2, z+18, Blocks.stonebrick, 1);
        place(w, x+18, y+2, z+18, Blocks.stone_brick_stairs, 1);
        place(w, x+2, y+3, z+18, Blocks.stone_stairs, 0);
        place(w, x+3, y+3, z+18, Blocks.stonebrick, 2);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+3, z+18, Blocks.air, 0);
        place(w, x+17, y+3, z+18, Blocks.stonebrick, 2);
        place(w, x+18, y+3, z+18, Blocks.stone_stairs, 1);
        place(w, x+3, y+4, z+18, Blocks.stone_stairs, 0);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+4, z+18, Blocks.air, 0);
        place(w, x+17, y+4, z+18, Blocks.stone_brick_stairs, 1);
        place(w, x+3, y+5, z+18, Blocks.stone_brick_stairs, 0);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+5, z+18, Blocks.air, 0);
        place(w, x+17, y+5, z+18, Blocks.stone_brick_stairs, 1);
        place(w, x+3, y+6, z+18, Blocks.stone_brick_stairs, 0);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+6, z+18, Blocks.air, 0);
        place(w, x+17, y+6, z+18, Blocks.stone_brick_stairs, 1);
        place(w, x+3, y+7, z+18, Blocks.stone, 6);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+7, z+18, Blocks.air, 0);
        place(w, x+17, y+7, z+18, Blocks.stone, 6);
        place(w, x+2, y+8, z+18, Blocks.stone_brick_stairs, 4);
        place(w, x+3, y+8, z+18, Blocks.stone, 6);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+8, z+18, Blocks.air, 0);
        place(w, x+17, y+8, z+18, Blocks.stone, 6);
        place(w, x+18, y+8, z+18, Blocks.stone_brick_stairs, 5);
        for(int dx=1; dx<3; dx++) place(w, x+dx, y+9, z+18, legends_concrete, 8);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+9, z+18, Blocks.air, 0);
        for(int dx=18; dx<20; dx++) place(w, x+dx, y+9, z+18, legends_concrete, 8);
        place(w, x+1, y+10, z+18, Blocks.stone_slab, 5);
        place(w, x+2, y+10, z+18, Blocks.double_stone_slab, 5);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+10, z+18, Blocks.double_stone_slab, 8);
        place(w, x+18, y+10, z+18, Blocks.double_stone_slab, 5);
        place(w, x+19, y+10, z+18, Blocks.stone_slab, 5);
        place(w, x+2, y+0, z+19, Blocks.stonebrick, 1);
        place(w, x+3, y+0, z+19, Blocks.stone, 0);
        for(int dx=4; dx<6; dx++) place(w, x+dx, y+0, z+19, Blocks.air, 0);
        for(int dx=6; dx<15; dx++) place(w, x+dx, y+0, z+19, Blocks.double_stone_slab, 8);
        for(int dx=15; dx<17; dx++) place(w, x+dx, y+0, z+19, Blocks.air, 0);
        place(w, x+17, y+0, z+19, Blocks.stone, 0);
        place(w, x+18, y+0, z+19, Blocks.stonebrick, 1);
        place(w, x+2, y+1, z+19, Blocks.stone_brick_stairs, 0);
        place(w, x+3, y+1, z+19, Blocks.stone, 0);
        for(int dx=4; dx<6; dx++) place(w, x+dx, y+1, z+19, Blocks.air, 0);
        place(w, x+6, y+1, z+19, Blocks.double_stone_slab, 8);
        for(int dx=7; dx<14; dx++) place(w, x+dx, y+1, z+19, Blocks.stone_stairs, 3);
        place(w, x+14, y+1, z+19, Blocks.double_stone_slab, 8);
        for(int dx=15; dx<17; dx++) place(w, x+dx, y+1, z+19, Blocks.air, 0);
        place(w, x+17, y+1, z+19, Blocks.stone, 0);
        place(w, x+18, y+1, z+19, Blocks.stone_brick_stairs, 1);
        place(w, x+2, y+2, z+19, Blocks.stone_brick_stairs, 0);
        place(w, x+3, y+2, z+19, Blocks.stone, 0);
        for(int dx=4; dx<6; dx++) place(w, x+dx, y+2, z+19, Blocks.air, 0);
        for(int dx=6; dx<15; dx++) place(w, x+dx, y+2, z+19, Blocks.double_stone_slab, 8);
        for(int dx=15; dx<17; dx++) place(w, x+dx, y+2, z+19, Blocks.air, 0);
        place(w, x+17, y+2, z+19, Blocks.stonebrick, 1);
        place(w, x+18, y+2, z+19, Blocks.stone_stairs, 1);
        place(w, x+2, y+3, z+19, Blocks.stone_stairs, 0);
        place(w, x+3, y+3, z+19, Blocks.stonebrick, 2);
        for(int dx=4; dx<7; dx++) place(w, x+dx, y+3, z+19, Blocks.air, 0);
        for(int dx=7; dx<14; dx++) place(w, x+dx, y+3, z+19, Blocks.double_stone_slab, 8);
        for(int dx=14; dx<17; dx++) place(w, x+dx, y+3, z+19, Blocks.air, 0);
        place(w, x+17, y+3, z+19, Blocks.stone, 0);
        place(w, x+18, y+3, z+19, Blocks.stone_stairs, 1);
        place(w, x+3, y+4, z+19, Blocks.stone_stairs, 0);
        for(int dx=4; dx<7; dx++) place(w, x+dx, y+4, z+19, Blocks.air, 0);
        place(w, x+7, y+4, z+19, Blocks.double_stone_slab, 8);
        for(int dx=8; dx<13; dx++) place(w, x+dx, y+4, z+19, Blocks.stone_stairs, 3);
        place(w, x+13, y+4, z+19, Blocks.double_stone_slab, 8);
        for(int dx=14; dx<17; dx++) place(w, x+dx, y+4, z+19, Blocks.air, 0);
        place(w, x+17, y+4, z+19, Blocks.stone_stairs, 1);
        place(w, x+3, y+5, z+19, Blocks.stone_brick_stairs, 0);
        for(int dx=4; dx<7; dx++) place(w, x+dx, y+5, z+19, Blocks.air, 0);
        for(int dx=7; dx<14; dx++) place(w, x+dx, y+5, z+19, Blocks.double_stone_slab, 8);
        for(int dx=14; dx<17; dx++) place(w, x+dx, y+5, z+19, Blocks.air, 0);
        place(w, x+17, y+5, z+19, Blocks.stone_brick_stairs, 1);
        place(w, x+3, y+6, z+19, Blocks.stone_brick_stairs, 0);
        for(int dx=4; dx<7; dx++) place(w, x+dx, y+6, z+19, Blocks.air, 0);
        for(int dx=7; dx<14; dx++) place(w, x+dx, y+6, z+19, Blocks.double_stone_slab, 8);
        for(int dx=14; dx<17; dx++) place(w, x+dx, y+6, z+19, Blocks.air, 0);
        place(w, x+17, y+6, z+19, Blocks.stone_brick_stairs, 1);
        place(w, x+3, y+7, z+19, Blocks.stone, 6);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+7, z+19, Blocks.air, 0);
        place(w, x+17, y+7, z+19, Blocks.stone, 6);
        place(w, x+2, y+8, z+19, Blocks.stone_brick_stairs, 4);
        place(w, x+3, y+8, z+19, Blocks.stone, 6);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+8, z+19, Blocks.air, 0);
        place(w, x+17, y+8, z+19, Blocks.stone, 6);
        place(w, x+18, y+8, z+19, Blocks.stone_brick_stairs, 5);
        for(int dx=1; dx<3; dx++) place(w, x+dx, y+9, z+19, legends_concrete, 8);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+9, z+19, Blocks.air, 0);
        for(int dx=18; dx<20; dx++) place(w, x+dx, y+9, z+19, legends_concrete, 8);
        place(w, x+1, y+10, z+19, Blocks.stone_slab, 5);
        place(w, x+2, y+10, z+19, Blocks.double_stone_slab, 5);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+10, z+19, Blocks.double_stone_slab, 8);
        place(w, x+18, y+10, z+19, Blocks.double_stone_slab, 5);
        place(w, x+19, y+10, z+19, Blocks.stone_slab, 5);
        place(w, x+2, y+0, z+20, Blocks.stonebrick, 1);
        place(w, x+3, y+0, z+20, Blocks.stone, 0);
        for(int dx=4; dx<6; dx++) place(w, x+dx, y+0, z+20, Blocks.air, 0);
        place(w, x+6, y+0, z+20, Blocks.stone, 6);
        place(w, x+7, y+0, z+20, Blocks.iron_bars, 0);
        for(int dx=8; dx<10; dx++) place(w, x+dx, y+0, z+20, Blocks.stone_button, 3);
        place(w, x+10, y+0, z+20, Blocks.iron_bars, 0);
        for(int dx=11; dx<13; dx++) place(w, x+dx, y+0, z+20, Blocks.stone_button, 3);
        place(w, x+13, y+0, z+20, Blocks.iron_bars, 0);
        place(w, x+14, y+0, z+20, Blocks.stone, 6);
        for(int dx=15; dx<17; dx++) place(w, x+dx, y+0, z+20, Blocks.air, 0);
        for(int dx=17; dx<19; dx++) place(w, x+dx, y+0, z+20, Blocks.stone, 0);
        place(w, x+2, y+1, z+20, Blocks.stone_stairs, 0);
        place(w, x+3, y+1, z+20, Blocks.stonebrick, 1);
        for(int dx=4; dx<6; dx++) place(w, x+dx, y+1, z+20, Blocks.air, 0);
        place(w, x+6, y+1, z+20, Blocks.stone, 6);
        place(w, x+7, y+1, z+20, Blocks.iron_bars, 0);
        for(int dx=8; dx<10; dx++) place(w, x+dx, y+1, z+20, Blocks.air, 0);
        place(w, x+10, y+1, z+20, Blocks.iron_bars, 0);
        for(int dx=11; dx<13; dx++) place(w, x+dx, y+1, z+20, Blocks.air, 0);
        place(w, x+13, y+1, z+20, Blocks.iron_bars, 0);
        place(w, x+14, y+1, z+20, Blocks.stone, 6);
        for(int dx=15; dx<17; dx++) place(w, x+dx, y+1, z+20, Blocks.air, 0);
        place(w, x+17, y+1, z+20, Blocks.stonebrick, 2);
        place(w, x+18, y+1, z+20, Blocks.stone_brick_stairs, 1);
        place(w, x+2, y+2, z+20, Blocks.stone_brick_stairs, 0);
        place(w, x+3, y+2, z+20, Blocks.stone, 0);
        for(int dx=4; dx<6; dx++) place(w, x+dx, y+2, z+20, Blocks.air, 0);
        place(w, x+6, y+2, z+20, Blocks.stone, 6);
        for(int dx=7; dx<9; dx++) place(w, x+dx, y+2, z+20, Blocks.iron_bars, 0);
        place(w, x+9, y+2, z+20, Blocks.air, 0);
        place(w, x+10, y+2, z+20, Blocks.iron_bars, 0);
        place(w, x+11, y+2, z+20, Blocks.air, 0);
        for(int dx=12; dx<14; dx++) place(w, x+dx, y+2, z+20, Blocks.iron_bars, 0);
        place(w, x+14, y+2, z+20, Blocks.stone, 6);
        for(int dx=15; dx<17; dx++) place(w, x+dx, y+2, z+20, Blocks.air, 0);
        place(w, x+17, y+2, z+20, Blocks.stonebrick, 2);
        place(w, x+18, y+2, z+20, Blocks.stone_brick_stairs, 1);
        place(w, x+2, y+3, z+20, Blocks.stone_brick_stairs, 0);
        place(w, x+3, y+3, z+20, Blocks.stonebrick, 2);
        for(int dx=4; dx<7; dx++) place(w, x+dx, y+3, z+20, Blocks.air, 0);
        place(w, x+7, y+3, z+20, Blocks.stone, 0);
        place(w, x+8, y+3, z+20, Blocks.iron_bars, 0);
        place(w, x+9, y+3, z+20, Blocks.air, 0);
        place(w, x+10, y+3, z+20, Blocks.iron_bars, 0);
        place(w, x+11, y+3, z+20, Blocks.air, 0);
        place(w, x+12, y+3, z+20, Blocks.iron_bars, 0);
        place(w, x+13, y+3, z+20, Blocks.stone, 0);
        for(int dx=14; dx<17; dx++) place(w, x+dx, y+3, z+20, Blocks.air, 0);
        place(w, x+17, y+3, z+20, Blocks.stonebrick, 2);
        place(w, x+18, y+3, z+20, Blocks.stone_brick_stairs, 1);
        place(w, x+3, y+4, z+20, Blocks.stone_stairs, 0);
        for(int dx=4; dx<7; dx++) place(w, x+dx, y+4, z+20, Blocks.air, 0);
        place(w, x+7, y+4, z+20, Blocks.stonebrick, 2);
        place(w, x+8, y+4, z+20, Blocks.iron_bars, 0);
        place(w, x+9, y+4, z+20, Blocks.air, 0);
        place(w, x+10, y+4, z+20, Blocks.iron_bars, 0);
        place(w, x+11, y+4, z+20, Blocks.air, 0);
        place(w, x+12, y+4, z+20, Blocks.iron_bars, 0);
        place(w, x+13, y+4, z+20, Blocks.stonebrick, 2);
        for(int dx=14; dx<17; dx++) place(w, x+dx, y+4, z+20, Blocks.air, 0);
        place(w, x+17, y+4, z+20, Blocks.stone_brick_stairs, 1);
        place(w, x+3, y+5, z+20, Blocks.stone_brick_stairs, 0);
        for(int dx=4; dx<7; dx++) place(w, x+dx, y+5, z+20, Blocks.air, 0);
        place(w, x+7, y+5, z+20, Blocks.stonebrick, 2);
        place(w, x+8, y+5, z+20, Blocks.iron_bars, 0);
        place(w, x+9, y+5, z+20, Blocks.stone_button, 3);
        place(w, x+10, y+5, z+20, Blocks.iron_bars, 0);
        place(w, x+11, y+5, z+20, Blocks.stone_button, 3);
        place(w, x+12, y+5, z+20, Blocks.iron_bars, 0);
        place(w, x+13, y+5, z+20, Blocks.stone, 6);
        for(int dx=14; dx<17; dx++) place(w, x+dx, y+5, z+20, Blocks.air, 0);
        place(w, x+17, y+5, z+20, Blocks.stone_brick_stairs, 1);
        place(w, x+3, y+6, z+20, Blocks.stone_brick_stairs, 0);
        for(int dx=4; dx<7; dx++) place(w, x+dx, y+6, z+20, Blocks.air, 0);
        for(int dx=7; dx<12; dx++) place(w, x+dx, y+6, z+20, Blocks.stone, 6);
        place(w, x+12, y+6, z+20, Blocks.stone, 0);
        place(w, x+13, y+6, z+20, Blocks.stonebrick, 2);
        for(int dx=14; dx<17; dx++) place(w, x+dx, y+6, z+20, Blocks.air, 0);
        place(w, x+17, y+6, z+20, Blocks.stone_brick_stairs, 1);
        place(w, x+3, y+7, z+20, Blocks.stone, 6);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+7, z+20, Blocks.air, 0);
        place(w, x+17, y+7, z+20, Blocks.stone, 6);
        place(w, x+2, y+8, z+20, Blocks.stone_brick_stairs, 4);
        place(w, x+3, y+8, z+20, Blocks.stone, 6);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+8, z+20, Blocks.air, 0);
        place(w, x+17, y+8, z+20, Blocks.stone, 6);
        place(w, x+18, y+8, z+20, Blocks.stone_brick_stairs, 5);
        place(w, x+0, y+9, z+20, Blocks.stone_button, 2);
        for(int dx=1; dx<3; dx++) place(w, x+dx, y+9, z+20, legends_concrete, 8);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+9, z+20, Blocks.air, 0);
        for(int dx=18; dx<20; dx++) place(w, x+dx, y+9, z+20, legends_concrete, 8);
        place(w, x+20, y+9, z+20, Blocks.stone_button, 1);
        place(w, x+1, y+10, z+20, Blocks.stone_slab, 5);
        place(w, x+2, y+10, z+20, Blocks.double_stone_slab, 5);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+10, z+20, Blocks.double_stone_slab, 8);
        place(w, x+18, y+10, z+20, Blocks.double_stone_slab, 5);
        place(w, x+19, y+10, z+20, Blocks.stone_slab, 5);
        place(w, x+2, y+0, z+21, Blocks.stone, 0);
        place(w, x+3, y+0, z+21, Blocks.stone, 6);
        for(int dx=4; dx<6; dx++) place(w, x+dx, y+0, z+21, Blocks.air, 0);
        place(w, x+6, y+0, z+21, Blocks.stone, 6);
        for(int dx=7; dx<14; dx++) place(w, x+dx, y+0, z+21, Blocks.air, 0);
        place(w, x+14, y+0, z+21, Blocks.stone, 6);
        for(int dx=15; dx<17; dx++) place(w, x+dx, y+0, z+21, Blocks.air, 0);
        for(int dx=17; dx<19; dx++) place(w, x+dx, y+0, z+21, Blocks.stone, 0);
        place(w, x+2, y+1, z+21, Blocks.stone_brick_stairs, 0);
        place(w, x+3, y+1, z+21, Blocks.stonebrick, 1);
        for(int dx=4; dx<6; dx++) place(w, x+dx, y+1, z+21, Blocks.air, 0);
        place(w, x+6, y+1, z+21, Blocks.stone, 6);
        for(int dx=7; dx<13; dx++) place(w, x+dx, y+1, z+21, Blocks.air, 0);
        place(w, x+13, y+1, z+21, Blocks.stone_button, 2);
        place(w, x+14, y+1, z+21, Blocks.stonebrick, 2);
        for(int dx=15; dx<17; dx++) place(w, x+dx, y+1, z+21, Blocks.air, 0);
        place(w, x+17, y+1, z+21, Blocks.stone, 0);
        place(w, x+18, y+1, z+21, Blocks.stone_stairs, 1);
        place(w, x+2, y+2, z+21, Blocks.stone_stairs, 0);
        place(w, x+3, y+2, z+21, Blocks.stonebrick, 1);
        for(int dx=4; dx<6; dx++) place(w, x+dx, y+2, z+21, Blocks.air, 0);
        place(w, x+6, y+2, z+21, Blocks.stone, 6);
        place(w, x+7, y+2, z+21, Blocks.stone_slab, 13);
        for(int dx=8; dx<13; dx++) place(w, x+dx, y+2, z+21, Blocks.air, 0);
        place(w, x+13, y+2, z+21, Blocks.stone_slab, 13);
        place(w, x+14, y+2, z+21, Blocks.stone, 0);
        for(int dx=15; dx<17; dx++) place(w, x+dx, y+2, z+21, Blocks.air, 0);
        place(w, x+17, y+2, z+21, Blocks.stone, 0);
        place(w, x+18, y+2, z+21, Blocks.stone_brick_stairs, 1);
        for(int dx=2; dx<4; dx++) place(w, x+dx, y+3, z+21, Blocks.stonebrick, 2);
        for(int dx=4; dx<7; dx++) place(w, x+dx, y+3, z+21, Blocks.air, 0);
        place(w, x+7, y+3, z+21, Blocks.stone, 0);
        for(int dx=8; dx<13; dx++) place(w, x+dx, y+3, z+21, Blocks.air, 0);
        place(w, x+13, y+3, z+21, Blocks.stone, 0);
        for(int dx=14; dx<17; dx++) place(w, x+dx, y+3, z+21, Blocks.air, 0);
        place(w, x+17, y+3, z+21, Blocks.stonebrick, 2);
        place(w, x+18, y+3, z+21, Blocks.stone, 0);
        place(w, x+3, y+4, z+21, Blocks.stonebrick, 2);
        for(int dx=4; dx<7; dx++) place(w, x+dx, y+4, z+21, Blocks.air, 0);
        place(w, x+7, y+4, z+21, Blocks.stonebrick, 2);
        for(int dx=8; dx<13; dx++) place(w, x+dx, y+4, z+21, Blocks.air, 0);
        place(w, x+13, y+4, z+21, Blocks.stonebrick, 2);
        for(int dx=14; dx<17; dx++) place(w, x+dx, y+4, z+21, Blocks.air, 0);
        place(w, x+17, y+4, z+21, Blocks.stonebrick, 1);
        place(w, x+3, y+5, z+21, Blocks.stone, 6);
        for(int dx=4; dx<7; dx++) place(w, x+dx, y+5, z+21, Blocks.air, 0);
        place(w, x+7, y+5, z+21, Blocks.stonebrick, 2);
        for(int dx=8; dx<13; dx++) place(w, x+dx, y+5, z+21, Blocks.air, 0);
        place(w, x+13, y+5, z+21, Blocks.stonebrick, 2);
        for(int dx=14; dx<17; dx++) place(w, x+dx, y+5, z+21, Blocks.air, 0);
        place(w, x+17, y+5, z+21, Blocks.stonebrick, 2);
        place(w, x+3, y+6, z+21, Blocks.stone, 6);
        for(int dx=4; dx<7; dx++) place(w, x+dx, y+6, z+21, Blocks.air, 0);
        for(int dx=7; dx<11; dx++) place(w, x+dx, y+6, z+21, Blocks.stone, 6);
        for(int dx=11; dx<13; dx++) place(w, x+dx, y+6, z+21, Blocks.stonebrick, 2);
        place(w, x+13, y+6, z+21, Blocks.stone, 0);
        for(int dx=14; dx<17; dx++) place(w, x+dx, y+6, z+21, Blocks.air, 0);
        place(w, x+17, y+6, z+21, Blocks.stonebrick, 2);
        place(w, x+3, y+7, z+21, Blocks.stone, 6);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+7, z+21, Blocks.air, 0);
        place(w, x+17, y+7, z+21, Blocks.stone, 6);
        place(w, x+2, y+8, z+21, Blocks.stone_brick_stairs, 4);
        place(w, x+3, y+8, z+21, Blocks.stone, 6);
        for(int dx=4; dx<17; dx++) place(w, x+dx, y+8, z+21, Blocks.air, 0);
        place(w, x+17, y+8, z+21, Blocks.stone, 6);
        place(w, x+18, y+8, z+21, Blocks.stone_brick_stairs, 5);
        place(w, x+0, y+9, z+21, Blocks.stone_button, 2);
        for(int dx=1; dx<3; dx++) place(w, x+dx, y+9, z+21, legends_concrete, 8);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+9, z+21, Blocks.air, 0);
        for(int dx=18; dx<20; dx++) place(w, x+dx, y+9, z+21, legends_concrete, 8);
        place(w, x+20, y+9, z+21, Blocks.stone_button, 1);
        place(w, x+1, y+10, z+21, Blocks.stone_slab, 5);
        place(w, x+2, y+10, z+21, Blocks.double_stone_slab, 5);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+10, z+21, Blocks.double_stone_slab, 8);
        place(w, x+18, y+10, z+21, Blocks.double_stone_slab, 5);
        place(w, x+19, y+10, z+21, Blocks.stone_slab, 5);
        for(int dx=2; dx<4; dx++) place(w, x+dx, y+0, z+22, Blocks.stonebrick, 1);
        for(int dx=4; dx<7; dx++) place(w, x+dx, y+0, z+22, Blocks.stone, 6);
        for(int dx=7; dx<14; dx++) place(w, x+dx, y+0, z+22, Blocks.air, 0);
        place(w, x+14, y+0, z+22, Blocks.stone, 6);
        place(w, x+15, y+0, z+22, Blocks.stone, 0);
        place(w, x+16, y+0, z+22, Blocks.stonebrick, 1);
        place(w, x+17, y+0, z+22, Blocks.stone, 0);
        place(w, x+18, y+0, z+22, Blocks.stonebrick, 1);
        for(int dx=2; dx<5; dx++) place(w, x+dx, y+1, z+22, Blocks.stonebrick, 1);
        place(w, x+5, y+1, z+22, Blocks.stone, 0);
        place(w, x+6, y+1, z+22, Blocks.stonebrick, 1);
        for(int dx=7; dx<13; dx++) place(w, x+dx, y+1, z+22, Blocks.air, 0);
        place(w, x+13, y+1, z+22, Blocks.lever, 2);
        for(int dx=14; dx<18; dx++) place(w, x+dx, y+1, z+22, Blocks.stonebrick, 1);
        place(w, x+18, y+1, z+22, Blocks.stone, 0);
        place(w, x+2, y+2, z+22, Blocks.stone, 0);
        place(w, x+3, y+2, z+22, Blocks.stonebrick, 1);
        place(w, x+4, y+2, z+22, Blocks.stonebrick, 2);
        for(int dx=5; dx<7; dx++) place(w, x+dx, y+2, z+22, Blocks.stone, 0);
        place(w, x+7, y+2, z+22, Blocks.stone_slab, 13);
        for(int dx=8; dx<13; dx++) place(w, x+dx, y+2, z+22, Blocks.air, 0);
        place(w, x+13, y+2, z+22, Blocks.stone_slab, 13);
        for(int dx=14; dx<17; dx++) place(w, x+dx, y+2, z+22, Blocks.stone, 0);
        place(w, x+17, y+2, z+22, Blocks.stonebrick, 2);
        place(w, x+18, y+2, z+22, Blocks.stone, 0);
        for(int dx=2; dx<4; dx++) place(w, x+dx, y+3, z+22, Blocks.stone, 0);
        place(w, x+4, y+3, z+22, Blocks.stonebrick, 2);
        place(w, x+5, y+3, z+22, Blocks.stone, 0);
        for(int dx=6; dx<8; dx++) place(w, x+dx, y+3, z+22, Blocks.stonebrick, 2);
        for(int dx=8; dx<13; dx++) place(w, x+dx, y+3, z+22, Blocks.air, 0);
        place(w, x+13, y+3, z+22, Blocks.stone, 0);
        place(w, x+14, y+3, z+22, Blocks.stonebrick, 2);
        place(w, x+15, y+3, z+22, Blocks.stone, 0);
        for(int dx=16; dx<19; dx++) place(w, x+dx, y+3, z+22, Blocks.stonebrick, 2);
        place(w, x+3, y+4, z+22, Blocks.wool, 8);
        place(w, x+4, y+4, z+22, Blocks.stonebrick, 1);
        place(w, x+5, y+4, z+22, Blocks.stone_stairs, 3);
        place(w, x+6, y+4, z+22, Blocks.stone_brick_stairs, 3);
        place(w, x+7, y+4, z+22, Blocks.stone, 6);
        for(int dx=8; dx<13; dx++) place(w, x+dx, y+4, z+22, Blocks.air, 0);
        place(w, x+13, y+4, z+22, Blocks.stone, 0);
        for(int dx=14; dx<16; dx++) place(w, x+dx, y+4, z+22, Blocks.stone_stairs, 3);
        place(w, x+16, y+4, z+22, Blocks.stone, 0);
        place(w, x+17, y+4, z+22, Blocks.wool, 8);
        place(w, x+3, y+5, z+22, Blocks.wool, 8);
        place(w, x+4, y+5, z+22, Blocks.stone, 0);
        for(int dx=5; dx<7; dx++) place(w, x+dx, y+5, z+22, Blocks.stone_brick_stairs, 3);
        place(w, x+7, y+5, z+22, Blocks.stonebrick, 2);
        for(int dx=8; dx<13; dx++) place(w, x+dx, y+5, z+22, Blocks.air, 0);
        place(w, x+13, y+5, z+22, Blocks.stonebrick, 2);
        for(int dx=14; dx<16; dx++) place(w, x+dx, y+5, z+22, Blocks.stone_brick_stairs, 3);
        place(w, x+16, y+5, z+22, Blocks.stonebrick, 2);
        place(w, x+17, y+5, z+22, Blocks.wool, 8);
        place(w, x+3, y+6, z+22, Blocks.wool, 8);
        place(w, x+4, y+6, z+22, Blocks.stonebrick, 2);
        for(int dx=5; dx<7; dx++) place(w, x+dx, y+6, z+22, Blocks.stone_brick_stairs, 3);
        for(int dx=7; dx<11; dx++) place(w, x+dx, y+6, z+22, Blocks.stone, 6);
        place(w, x+11, y+6, z+22, Blocks.stone, 0);
        for(int dx=12; dx<14; dx++) place(w, x+dx, y+6, z+22, Blocks.stonebrick, 2);
        for(int dx=14; dx<16; dx++) place(w, x+dx, y+6, z+22, Blocks.stone_brick_stairs, 3);
        place(w, x+16, y+6, z+22, Blocks.stonebrick, 2);
        place(w, x+17, y+6, z+22, Blocks.wool, 8);
        place(w, x+3, y+7, z+22, Blocks.wool, 8);
        for(int dx=4; dx<12; dx++) place(w, x+dx, y+7, z+22, Blocks.stone, 6);
        for(int dx=12; dx<15; dx++) place(w, x+dx, y+7, z+22, Blocks.stonebrick, 2);
        for(int dx=15; dx<17; dx++) place(w, x+dx, y+7, z+22, Blocks.stone, 6);
        place(w, x+17, y+7, z+22, Blocks.wool, 8);
        place(w, x+2, y+8, z+22, Blocks.stone_brick_stairs, 4);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+8, z+22, Blocks.stone, 6);
        place(w, x+18, y+8, z+22, Blocks.stone_brick_stairs, 5);
        for(int dx=1; dx<3; dx++) place(w, x+dx, y+9, z+22, legends_concrete, 8);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+9, z+22, Blocks.air, 0);
        for(int dx=18; dx<20; dx++) place(w, x+dx, y+9, z+22, legends_concrete, 8);
        place(w, x+1, y+10, z+22, Blocks.stone_slab, 5);
        place(w, x+2, y+10, z+22, Blocks.double_stone_slab, 5);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+10, z+22, Blocks.double_stone_slab, 8);
        place(w, x+18, y+10, z+22, Blocks.double_stone_slab, 5);
        place(w, x+19, y+10, z+22, Blocks.stone_slab, 5);
        place(w, x+2, y+0, z+23, Blocks.wool, 8);
        place(w, x+3, y+0, z+23, Blocks.stone, 6);
        place(w, x+4, y+0, z+23, Blocks.stonebrick, 1);
        place(w, x+5, y+0, z+23, Blocks.stone, 6);
        place(w, x+6, y+0, z+23, Blocks.stonebrick, 1);
        for(int dx=7; dx<14; dx++) place(w, x+dx, y+0, z+23, Blocks.air, 0);
        place(w, x+14, y+0, z+23, Blocks.stonebrick, 1);
        place(w, x+15, y+0, z+23, Blocks.stone, 0);
        for(int dx=16; dx<18; dx++) place(w, x+dx, y+0, z+23, Blocks.stonebrick, 1);
        place(w, x+18, y+0, z+23, Blocks.wool, 8);
        place(w, x+2, y+1, z+23, Blocks.wool, 8);
        place(w, x+3, y+1, z+23, Blocks.stonebrick, 1);
        place(w, x+4, y+1, z+23, Blocks.stone_stairs, 3);
        place(w, x+5, y+1, z+23, Blocks.stone_brick_stairs, 3);
        place(w, x+6, y+1, z+23, Blocks.stonebrick, 1);
        for(int dx=7; dx<14; dx++) place(w, x+dx, y+1, z+23, Blocks.air, 0);
        place(w, x+14, y+1, z+23, Blocks.stonebrick, 1);
        for(int dx=15; dx<17; dx++) place(w, x+dx, y+1, z+23, Blocks.stone_brick_stairs, 3);
        place(w, x+17, y+1, z+23, Blocks.stone, 0);
        place(w, x+18, y+1, z+23, Blocks.wool, 8);
        place(w, x+2, y+2, z+23, Blocks.wool, 8);
        place(w, x+3, y+2, z+23, Blocks.stone, 0);
        place(w, x+4, y+2, z+23, Blocks.stone_stairs, 3);
        place(w, x+5, y+2, z+23, Blocks.stone_brick_stairs, 3);
        place(w, x+6, y+2, z+23, Blocks.stone, 0);
        place(w, x+7, y+2, z+23, Blocks.stone_slab, 13);
        for(int dx=8; dx<13; dx++) place(w, x+dx, y+2, z+23, Blocks.air, 0);
        place(w, x+13, y+2, z+23, Blocks.stone_slab, 13);
        place(w, x+14, y+2, z+23, Blocks.stone, 0);
        place(w, x+15, y+2, z+23, Blocks.stone_stairs, 3);
        place(w, x+16, y+2, z+23, Blocks.stone_brick_stairs, 3);
        place(w, x+17, y+2, z+23, Blocks.stonebrick, 2);
        place(w, x+18, y+2, z+23, Blocks.wool, 8);
        place(w, x+2, y+3, z+23, Blocks.wool, 8);
        for(int dx=3; dx<5; dx++) place(w, x+dx, y+3, z+23, Blocks.stone, 0);
        place(w, x+5, y+3, z+23, Blocks.stone_stairs, 3);
        place(w, x+6, y+3, z+23, Blocks.stone_brick_stairs, 3);
        place(w, x+7, y+3, z+23, Blocks.stonebrick, 2);
        for(int dx=8; dx<13; dx++) place(w, x+dx, y+3, z+23, Blocks.air, 0);
        place(w, x+13, y+3, z+23, Blocks.stone, 0);
        place(w, x+14, y+3, z+23, Blocks.stone_brick_stairs, 3);
        place(w, x+15, y+3, z+23, Blocks.stone_stairs, 3);
        place(w, x+16, y+3, z+23, Blocks.stonebrick, 2);
        place(w, x+17, y+3, z+23, Blocks.stone, 6);
        place(w, x+18, y+3, z+23, Blocks.wool, 8);
        place(w, x+7, y+4, z+23, Blocks.stone_stairs, 3);
        for(int dx=8; dx<13; dx++) place(w, x+dx, y+4, z+23, Blocks.air, 0);
        place(w, x+13, y+4, z+23, Blocks.stone_brick_stairs, 3);
        for(int dx=8; dx<13; dx++) place(w, x+dx, y+5, z+23, Blocks.air, 0);
        for(int dx=8; dx<13; dx++) place(w, x+dx, y+6, z+23, Blocks.stone_slab, 5);
        place(w, x+2, y+8, z+23, Blocks.stone_brick_stairs, 4);
        for(int dx=3; dx<18; dx++) place(w, x+dx, y+8, z+23, Blocks.stone_brick_stairs, 7);
        place(w, x+18, y+8, z+23, Blocks.stone_brick_stairs, 5);
        for(int dx=1; dx<20; dx++) place(w, x+dx, y+9, z+23, legends_concrete, 8);
        place(w, x+1, y+10, z+23, Blocks.stone_slab, 5);
        for(int dx=2; dx<19; dx++) place(w, x+dx, y+10, z+23, Blocks.double_stone_slab, 5);
        place(w, x+19, y+10, z+23, Blocks.stone_slab, 5);
        place(w, x+0, y+9, z+24, Blocks.stone_button, 2);
        for(int dx=1; dx<20; dx++) place(w, x+dx, y+9, z+24, legends_concrete, 8);
        place(w, x+20, y+9, z+24, Blocks.stone_button, 1);
        for(int dx=1; dx<20; dx++) place(w, x+dx, y+10, z+24, Blocks.stone_slab, 5);
    }

    private static void place(World w,int x,int y,int z,Block b,int m){
        if(b!=null) w.setBlock(x,y,z,b,m,2);
    }

	private boolean canPlaceOnSolidGround(World w, int x, int y, int z, int width, int length) {

		// dont generate if the whole rectangle isnt already in memory
		if (!w.checkChunksExist(x, y - 1, z, x + width - 1, y - 1, z + length - 1))
			return false;

		for (int dx = 0; dx < width; dx++)
			for (int dz = 0; dz < length; dz++) {
				Block b = w.getBlock(x + dx, y - 1, z + dz);

				if (b == null || !b.getMaterial().isSolid() || // air, leaves, etc.
						b.getMaterial().isLiquid()) // water / lava
					return false;
			}
		return true;
	}

	public static boolean intersectsPad(int x, int z) {
		for (AxisAlignedBB bb : ALL_PADS)
			if (bb.minX <= x && x <= bb.maxX && bb.minZ <= z && z <= bb.maxZ)
				return true;
		return false;
	}
}
